### PR TITLE
Use HTCondor python API

### PR DESCRIPTION
**Pull request by mesmith75**
Start on #1916 

- [x] Submit
- [x] Kill
- [x] Resubmit
- [x] Query
- [x] peek
- [ ] Hold, release + other extras

### CODE REVIEW

**Review by egede — DISMISSED** [review]

**Comment by egede** [comment]
Remember that there is a new directory `GangaCore/test/Condor` where tests of HTCondor can be placed.

**Comment by mesmith75** [comment]
The monitoring is currently returning an error:
```python
ERROR    Exception raised executing 'updateMonitoringInformation' in Thread 'Backend Monitor':
Traceback (most recent call last):
  File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 124, in __worker_thread
    result = item.command_input.function(*these_args, **item.command_input.kwargs)
  File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/Lib/Condor/Condor.py", line 480, in updateMonitoringInformation
    stati = schedd.query(constraint = expr_tree, projection = ["ClusterId", "ProcId", "JobStatus", "RemoteUserCpu","AllRemoteHosts"])
  File "/afs/cern.ch/user/m/masmith/gangatest_python3/lib/python3.6/site-packages/htcondor/_deprecation.py", line 111, in wrapper
    return method(self, *args, **kwargs)
  File "/afs/cern.ch/user/m/masmith/gangatest_python3/lib/python3.6/site-packages/htcondor/_lock.py", line 69, in wrapper
    rv = func(*args, **kwargs)
htcondor.HTCondorIOError: Failed to fetch ads from schedd, errmsg=SECMAN:2007:Failed to end classad message.
```
I am not sure if this is a fatal issue or something we can hide

**Comment by mesmith75** [comment]
This is giving an error when trying to access a sandbox:
```python
Traceback (most recent call last):
  File "./Ganga_13_Executable", line 74, in getPackedInputSandbox
    with closing(tarfile.open(tarpath, "r:*")) as tf:
  File "/usr/lib64/python3.6/tarfile.py", line 1573, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib64/python3.6/tarfile.py", line 1638, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/usr/lib64/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: '/afs/cern.ch/work/m/masmith/GangaTest/test/repos/workspace/masmith/LocalXML/13/input/_input_sandbox_13_master.tgz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Ganga_13_Executable", line 146, in <module>
    getPackedInputSandbox( inFile )
  File "./Ganga_13_Executable", line 77, in getPackedInputSandbox
    raise Exception("Error opening tar file: %s" % tarpath)
Exception: Error opening tar file: /afs/cern.ch/work/m/masmith/GangaTest/test/repos/workspace/masmith/LocalXML/13/input/_input_sandbox_13_master.tgz
```
It looks as if these jobs cannot access the AFS file system

**Comment by egede** [comment]
Link to [CERN helpdesk request](https://cern.service-now.com/service-portal?id=ticket&table=u_request_fulfillment&n=RQF1836813)

**Comment by egede** [comment]
So, it seems like it is possible to preserve the kerberos tickets using the Python API as well. Just make sure that the code for that is written such that it doesn't break the `Condor` backend in places without afs.

**Comment by mesmith75** [comment]
The issue with the kerberos credentials is fixed.

I *think* this shouldn't matter for other systems as the extras required look fairly agnostic to what is underneath, assuming the condor system is correctly configured on the submitting machine.

**Comment by mesmith75** [comment]
@egede I think this is ready - all the existing functionality has been updated (there is no python binding for `condor_tail` yet).

I'll put any other extras in another PR, along with the fix to the outputfiles.

**Review by alexanderrichards — APPROVED** [review]

**Review by egede — APPROVED** [review]

**Pull request merged**
