### PR TITLE
Release 7.1.15

### PR DESCRIPTION
**Pull request by mesmith75**
Last release with a deprecation warning.

### CODE REVIEW

**Review by egede — DISMISSED** [review]
Can we time it such that this release and the python3 release are made with only a very short time in between. The idea is that only a small number of users should see this message (but not be able to upgrade as the release is not there).

**Comment by mesmith75** [comment]
Yes. If we merge the tests into the python3 branch I'll swap over the CVMFS DEV version to that so users can test it for a week. The we can release this, followed by 8.

**Review by egede — DISMISSED** [review]

**Review by alexanderrichards — DISMISSED** [review]

**Review by alexanderrichards — APPROVED** [review]

**Comment by mesmith75** [comment]
So this has been released. Once the tests are done we can merge.

**Comment by alexanderrichards** [comment]
sure thing. Do we need to merge develop back into this branch before we merge?

**Comment by alexanderrichards** [comment]
sorry, was on the wrong branch :wink: Yes once tests pass, merge this then we probably need one more merge from develop into python3? To pick up things like #1499?

**Comment by mesmith75** [comment]
yes

**Pull request merged**
