### PR TITLE
Fixes fro Bender applictaions

### PR DESCRIPTION
**Pull request by VanyaBelyaev**
Few fixes for Bender applications

### CODE REVIEW

**Comment by egede** [comment]
test this please

**Comment by rob-c** [comment]
would it be worth making some tests to ensure that bugs aren't added by any future changes to the base class?

**Comment by VanyaBelyaev** [comment]
@rob-c Hi Rob, I'll provide some test, but it will take some time (probably next week).  I need some help and instructions how to run the tests.  The trivial 'ganga -test xxx' does not work for me - it complains for missing pytest...

**Comment by egede** [comment]
retest this please

**Pull request merged**
