### PR TITLE
Remove un-needed proxy methods and unused imports

### PR DESCRIPTION
**Pull request by rob-c**
This PR builds on #707 and removes some dead code as well as removing un-needed proxy methods from code which doesn't need to know about the proxy.

Specifically I've removed a lot of _safe_ un-needed calls to `stripProxy` and `getName` which pull in the Proxy.
In addition I've removed a lot of unused imports.

This will merge atop #707 if everything goes well and between the 2 PR a lot of un-needed proxy manipulation behind the scenes will have been removed.

The 2 areas where I haven't removed `stripProxy/addProxy` calls are the Proxy Registry classes and Tasks. Both of these require a bit of care and in the latter I think I can reduce the number of calls to these methods but these require being careful.

Edit: I've integrated #711 to reduce problems when automatically examining the code

### CODE REVIEW

**Comment by mesmith75** [comment]
Do we want to try and merge this? I imagine a lot of the code has changed since August but a cleanup would be nice?

**Comment by rob-c** [comment]
@mesmith75 I was wanting to move down this line but won't have time to look at this over the week. Feel free to adopt the branch and continue as the next time I'll likely get to play with this will be next weekend.

**Comment by mesmith75** [comment]
ok, can i rebase this to develop?

**Comment by rob-c** [comment]
This might as well be regenerated from scratch, but it's just an example of code cleanup so can be done in the future.

**Pull request closed without merging**
