### PR TITLE
Feature/slurm

### PR DESCRIPTION
**Pull request by NickHastings**
Hi,

apologies in advance if breach protocol in anyway, this is my first pull request here.

I've added a backend for the Slurm batch system. I've done some testing and it works for me.
Against Ganga 6.7.4 I've tested with a simple
j = Job()
j.backend = Slurm(extraopts="--account foo-bar-baz")
j.sumbit()

With Ganga 6.6.4 (and some earlier versions) I've also tested it with some ND280Tasks in runND280RDP() from my feature/ND280 branch. I'm unable to do the same tests with Ganga 6.7.4 because the transform._getParent() returns and NoneType just like in https://www.bountysource.com/issues/50702176-un-friendly-errors-when-there-is-a-mis-configuration
BTW any hits on this problem would be appreciated :-)

Anyway it would be great if this could be merged into Ganga main.

Thanks,

Nick.

### CODE REVIEW

**Comment by drmarkwslater** [comment]
Thanks for this @NickHastings ! This looks good, but the issue now is that your forked repo is out of date with the state of Ganga at the moment so it can't be merged. There a few things you can do:

1. Follow the instructions here to update the repo and this branch/PR (note: change `master` for `develop`):

https://help.github.com/articles/syncing-a-fork/

2. Delete your repo (after making sure you've backed up your changes!), re-fork and re-apply the changes

3. Let me apply the changes for you 😄 

I really don't mind which you'd prefer to do, but at the moment we can't merge because of conflicts

**Comment by drmarkwslater** [comment]
retest this please

**Comment by egede** [comment]
@drmarkwslater Can you look at the Task related bug reported here as well. That seems to be what is preventing the update to the current development branch.

**Comment by NickHastings** [comment]
@drmarkwslater I rebased feaure/Slurm to the develop branch. I had to make one manual fix. I tested it with 

j = Job()
j.backend = Slurm(extraopts="--account foo-bar-baz")
j.sumbit()

The job was submitted and run correctly. ganga seemed to report its state correctly during this. I think it's all good to go.

**Comment by NickHastings** [comment]
@drmarkwslater do I need to make a new pull request now? Also, should I be doing something about the checks/tests?

**Comment by mesmith75** [comment]
@NickHastings I think this is OK as is. We are having some testing issues which we'll hopefully fix in the next few days. Sorry for the delay.

**Comment by egede** [comment]
test please

**Comment by egede** [comment]
@mesmith75 Testing is not starting on this externally supplied PR - I guess this has to do with the changes we made in when PRs are tested?

**Comment by mesmith75** [comment]
test this please

**Comment by mesmith75** [comment]
ok to test

**Comment by mesmith75** [comment]
test this please

**Comment by mesmith75** [comment]
test this please

**Comment by mesmith75** [comment]
Are we ready to merge this?

**Review by egede — APPROVED** [review]
Thus looks good. Sorry for the long time it took to merge this, but we are now getting back to speed.

**Comment by will-cern** [comment]
Thanks. @drmarkwslater will this appear as "ganga athena --slurm ..." for submission of atlas code to slurm backends ?

Thanks
Will

**Comment by NickHastings** [comment]
Hi,

thanks for doing the merge. Any chance someone could look at the issue when moving from Ganga 6.6.4  to 6.7.4 that I mentioned in the original post? Or perhaps it's best if I submit an Issue for it?
Once that is sorted I'll be able merge the updated  stuff under GangaND280 from my feature/ND280 branch.

Cheers,

Nick.

**Comment by mesmith75** [comment]
Could you open an issue for it please? I think tasks in general need a bit of attention.

**Pull request merged**
