### PR TITLE
Adding GangaDirac test Dockerfile.

### PR DESCRIPTION
**Pull request by alexanderrichards**

### CODE REVIEW

**Comment by alexanderrichards** [comment]
alex test

**Comment by alexanderrichards** [comment]
alex test

**Comment by egede** [comment]
Did you check if the `gangage` certificate is indeed registered in the `gridpp` VO?

**Comment by alexanderrichards** [comment]
alex test

**Comment by alexanderrichards** [comment]
> Did you check if the gangage certificate is indeed registered in the gridpp VO?

not yet

**Comment by JinNamkung** [comment]
alex test

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
alex test

**Comment by JinNamkung** [comment]
retest this please

**Comment by alexanderrichards** [comment]
alex test

**Comment by alexanderrichards** [comment]
alex test

**Comment by JinNamkung** [comment]
retest this please

**Comment by alexanderrichards** [comment]
alex test

**Comment by alexanderrichards** [comment]
dirac test

**Comment by alexanderrichards** [comment]
dirac test

**Comment by alexanderrichards** [comment]
dirac test

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
just checking

**Comment by JinNamkung** [comment]
test

**Comment by JinNamkung** [comment]
just checking

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
alex test

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by alexanderrichards** [comment]
alex test

**Comment by JinNamkung** [comment]
retest this please

**Comment by alexanderrichards** [comment]
dirac test

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by alexanderrichards** [comment]
hi Jin, hows it going?

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
Ganga test

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
Ganga test

**Comment by JinNamkung** [comment]
Dirac test

**Comment by JinNamkung** [comment]
LHCb test

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
retest this please

**Comment by JinNamkung** [comment]
Ganga test

**Comment by JinNamkung** [comment]
Dirac test

**Comment by JinNamkung** [comment]
LHCb test

**Comment by egede** [comment]
This has been done elsewhere.

**Pull request closed without merging**
