### PR TITLE
Add gdown dependency

### PR DESCRIPTION
**Pull request by egede**
Missing dependency added.

### CODE REVIEW

**Comment by DumbMachine** [comment]
@egede do we want to add a `gdown` as a dependency or [use a simple `wget` call to download the files?](https://github.com/ganga-devs/ganga/pull/1791#issuecomment-706552599)

**Comment by egede** [comment]
I first removed gdown and just used urlretrieve. But then realised it gave the nice progress bar. I prefer to keep it. Also prefer it to external unix commands.

**Comment by DumbMachine** [comment]
Agreed, after testing the [removeGdown](https://github.com/ganga-devs/ganga/tree/removeGdown) branch that works using `wget` I would say creating a dangling process for a download is not the right choice.

**Review by DumbMachine — APPROVED** [review]

**Comment by mesmith75** [comment]
@egede Does this also need to update the `requirements.txt`?

**Comment by egede** [comment]
> @egede Does this also need to update the requirements.txt?
No, I believe the `-e` option in `requirements.txt` means that everything from `setup.py` is included.

**Pull request merged**
