### PR TITLE
Fix Condor script

### LINKED ISSUE #1199: Condor() backend fails trying to copy file to node
When I submit a ganga job via the `Condor()` backend, I get the following error

```
Traceback (most recent call last):
  File "/var/lib/condor/execute/dir_21888/condor_exec.exe", line 161, in <module>
    shutil.copy(inFile, os.path.join(os.getcwd(), os.path.basename(inFile)))
  File "/usr/lib64/python2.7/shutil.py", line 133, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 83, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `ntuple_maker_mc_12103091_2011.py` and `/var/lib/condor/execute/dir_21888/ntuple_maker_mc_12103091_2011.py` are the same file
```

where `ntuple_maker_mc_12103091_2011.py` is my DaVinci submission script.

I believe the offending lines are: 
* https://github.com/ganga-devs/ganga/blob/47825403bdb9f6d6123d1b6745751f0711318d15/python/GangaCore/Lib/Condor/Condor.py#L288-L290
* https://github.com/ganga-devs/ganga/blob/47825403bdb9f6d6123d1b6745751f0711318d15/python/GangaCore/Lib/Condor/Condor.py#L315-L319
such that `shutil.copy` effectively ends up trying to copy the file over itself.

### PR DESCRIPTION
**Pull request by mesmith75**
Fixes #1199 .

I *think* the issues is the taking of the `basename` that was giving a effectively `cp somefile.py /path/to/cwd/somefile.py` where really it should include the original file path to copy it to the cwd.

Needs testing. @nasfarley88 Could you try this?

### CODE REVIEW

**Comment by natfarleydev** [comment]
@mesmith75 I'm happy to test. What's the best way to do this with the LHCb software stack?

**Comment by mesmith75** [comment]
@nasfarley88 Make yourself a clean virtualenv and install with pip via:
`pip install git+https://github.com/ganga-devs/ganga.git@condorFix`

**Comment by natfarleydev** [comment]
Unfortunately, LHCb does something special with their ganga (which I don't fully understand) so that I get the following error:

```
Repository 'tasks' object #18 is not accessible because of an InaccessibleObjectError: Repository 'tasks' object #18 is not accessible because of a PluginManagerError: PluginManagerError: (PluginManagerError(...), u"cannot find 'LHCbTask' in a category 'tasks', or elsewhere")
```

(This is once I have gone into SL6, then run the group login script for LHCb)

**Comment by natfarleydev** [comment]
Full error is:
```
ERROR    #1 Error(s) Loading File: /home/nasf/gangadir/repository/nasf/LocalXML/6.0/tasks/0xxx/18/data
ERROR    #1 Error(s) Loading File: /home/nasf/gangadir/repository/nasf/LocalXML/6.0/tasks/0xxx/18/data
ERROR    err: PluginManagerError: (PluginManagerError(...), u"cannot find 'LHCbTask' in a category 'tasks', or elsewhere")
ERROR    err: PluginManagerError: (PluginManagerError(...), u"cannot find 'LHCbTask' in a category 'tasks', or elsewhere")
ERROR    #1 Error(s) Loading File: /home/nasf/gangadir/repository/nasf/LocalXML/6.0/tasks/0xxx/18/data~
ERROR    #1 Error(s) Loading File: /home/nasf/gangadir/repository/nasf/LocalXML/6.0/tasks/0xxx/18/data~
ERROR    err: PluginManagerError: (PluginManagerError(...), u"cannot find 'LHCbTask' in a category 'tasks', or elsewhere")
ERROR    err: PluginManagerError: (PluginManagerError(...), u"cannot find 'LHCbTask' in a category 'tasks', or elsewhere")
ERROR    XML File failed to load for Job id: 18
ERROR    XML File failed to load for Job id: 18
ERROR    Actual Error was:
Repository 'tasks' object #18 is not accessible because of an InaccessibleObjectError: Repository 'tasks' object #18 is not accessible because of an PluginManagerError: PluginManagerError: (PluginManagerError(...), u"cannot find 'LHCbTask' in a category 'tasks', or elsewhere")
ERROR    Actual Error was:
Repository 'tasks' object #18 is not accessible because of an InaccessibleObjectError: Repository 'tasks' object #18 is not accessible because of an PluginManagerError: PluginManagerError: (PluginManagerError(...), u"cannot find 'LHCbTask' in a category 'tasks', or elsewhere")
ERROR    Loading: 18 into incomplete_objects to avoid loading it again in future
ERROR    Loading: 18 into incomplete_objects to avoid loading it again in future
```
And this happens for (presumably) every job in the ganga registry.

**Comment by mesmith75** [comment]
@nasfarley88 it didn't find the LHCb.ini config - I think that is an omission from us.

You need to set the environment variable GANGA_CONFIG_PATH to be
/cvmfs/ganga.cern.ch/Ganga/install/7.0.1/ganga/GangaLHCb/LHCb.ini

**Comment by natfarleydev** [comment]
When I do that, ganga shuts down automatically
```
$ GANGA_CONFIG_PATH=/cvmfs/ganga.cern.ch/Ganga/install/7.0.1/ganga/GangaLHCb/LHCb.ini ganga
WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7
*** Welcome to Ganga ***
Version: 7.0.1 - DEV
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.
This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.
ERROR    file /home/nasf/.gangarc was created by a development release (Ganga-6-7-2)
ERROR    try -g option to create valid ~/.gangarc
INFO     reading config file /home/nasf/.gangarc
INFO     reading config file /cvmfs/ganga.cern.ch/Ganga/install/7.0.1/ganga/GangaLHCb/LHCb.ini
INFO     reading config file /cvmfs/lhcb.cern.ch/lib/GangaConfig/config/6-7-2/GangaLHCb.ini
INFO     Using LHCbDirac version v9r1p9
WARNING  Cannot find job with id 11. Maybe reset this unit with: tasks(5).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 11. Maybe reset this unit with: tasks(5).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 11. Maybe reset this unit with: tasks(5).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 11. Maybe reset this unit with: tasks(5).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 14. Maybe reset this unit with: tasks(7).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 14. Maybe reset this unit with: tasks(7).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 14. Maybe reset this unit with: tasks(7).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 14. Maybe reset this unit with: tasks(7).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 17. Maybe reset this unit with: tasks(8).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 17. Maybe reset this unit with: tasks(8).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 17. Maybe reset this unit with: tasks(8).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 17. Maybe reset this unit with: tasks(8).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 19. Maybe reset this unit with: tasks(9).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 19. Maybe reset this unit with: tasks(9).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 19. Maybe reset this unit with: tasks(9).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 19. Maybe reset this unit with: tasks(9).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 20. Maybe reset this unit with: tasks(10).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 20. Maybe reset this unit with: tasks(10).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 20. Maybe reset this unit with: tasks(10).transforms[0].resetUnit(0)
WARNING  Cannot find job with id 20. Maybe reset this unit with: tasks(10).transforms[0].resetUnit(0)
WARNING  Incorrect index cache of 'jobs' object #289 was corrected!
WARNING  Incorrect index cache of 'jobs' object #288 was corrected!
WARNING  Incorrect index cache of 'jobs' object #287 was corrected!
WARNING  Incorrect index cache of 'jobs' object #286 was corrected!
WARNING  Incorrect index cache of 'jobs' object #285 was corrected!
WARNING  Job status re-updated after potential force-close
CRITICAL undefined state for job 185, status=set(['new'])
CRITICAL undefined state for job 185, status=set(['new'])
JobStatusError: forbidden status transition of job 185 from "submitting" to "None"
(consider --debug option for more information)
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown
```

**Comment by mesmith75** [comment]
That looks like an issue from #1193. Can you try setting `DisableLoadCheck' under the `Registry` section of your .gangarc to `True` ?

**Comment by natfarleydev** [comment]
New error, so I think #1199 might be fixed? 

```
INFO     submitting job 297
INFO     job 297 status changed to "submitting"
INFO     Preparing GaudiExec application.
INFO     Make-ing target 'ganga-input-sandbox'     (This may take a few minutes depending on the size of your project)
ERROR    Failed to execute command: /tmp/tmpqDnXvc.sh
ERROR    Failed to execute command: /tmp/tmpqDnXvc.sh
ERROR    Tried to execute command in: /disk/homedisk/home/nasf/git/rootless-broccoli/ntuple-maker/DaVinciDev_v39r1p1
ERROR    Tried to execute command in: /disk/homedisk/home/nasf/git/rootless-broccoli/ntuple-maker/DaVinciDev_v39r1p1
ERROR    StdErr: WARNING : using environment variable CMTSITE for cmtsite
WARNING : using environment variable User_release_area for userarea
WARNING : using environment variable VO_LHCB_SW_DIR for sharedarea
./run: line 21: ./build_env.sh: No such file or directory
ERROR    StdErr: WARNING : using environment variable CMTSITE for cmtsite
WARNING : using environment variable User_release_area for userarea
WARNING : using environment variable VO_LHCB_SW_DIR for sharedarea
./run: line 21: ./build_env.sh: No such file or directory
ERROR    GangaException: Failed to Execute command
ERROR    GangaException: Failed to Execute command
ERROR    GangaException: Failed to Execute command ... reverting job 297 to the new status
ERROR    GangaException: Failed to Execute command ... reverting job 297 to the new status
INFO     job 297 status changed to "new"
```

**Comment by mesmith75** [comment]
It turns out cern batch uses Condor these days. I was able to reproduce the original error. This looks to have fixed it.

@nasfarley88 That looks like the building of the cmake project failed.

**Comment by mesmith75** [comment]
Could someone please review this?

**Review by alexanderrichards — APPROVED** [review]

**Pull request merged**
