### PR TITLE
Jenkins tests

### PR DESCRIPTION
**Pull request by mesmith75**

### CODE REVIEW

**Comment by mesmith75** [comment]
The tests are running now and some are even passing.

**Comment by mesmith75** [comment]
Down to just a handful.

~~But we have somehow broken lazy-loading.~~ fixed

**Comment by mesmith75** [comment]
Success!

**Review by egede — APPROVED** [review]
Heroic work Mark. I think that we are ready for Ganga 8 now.

**Review by alexanderrichards — APPROVED** [review]
Amazing job!

**Comment by alexanderrichards** [comment]
due to the large number of bitsy commits, I suggest we squash merge this branch with a single comment like "Fix Jenkins Tests". This will hopefully make the commit history of the python 3 branch easier to traverse later on.

**Pull request merged**
