### PR TITLE
Remove OutputData from LHCb

### PR DESCRIPTION
**Pull request by mesmith75**
I have removed the file with the OutputData class definition and the imports from the other files in the LHCb directory.

### CODE REVIEW

**Comment by alexanderrichards** [comment]
add to whitelist

**Comment by milliams** [comment]
test this please

**Comment by alexanderrichards** [comment]
beat you to it this time @milliams :wink:

**Comment by alexanderrichards** [comment]
mark this branch appears to be out of date. Can you merge/rebase it? Alternatively we could try pressing the update branch button here at the bottom of the PR...do we trust that yet @milliams :wink: ..scary automatic stuff

**Comment by milliams** [comment]
This looks good to me. As long as there's no schema compatibility problems :+1:

@alexanderrichards The update button is relatively safe. It does a merge from `develop` into this. The merge commit it creates will usually be fast-forwarded away when it is merged into `develop` anyway. If there are any conflicts then it will not let you do it and will require manual intervention.

**Comment by mesmith75** [comment]
I think that has worked.

**Comment by alexanderrichards** [comment]
Only problem then I foresee is if users already have one of these objects in their repo or box.
However I believe that these objects haven't been used in LHCb workflows for some time right @rob-c? In which case we should be ok.

Go for merge from me :+1:

**Pull request merged**
