### PR TITLE
Modernise Shell.py

### LINKED ISSUE #2105: Refactor use of shell command
Much of the `ganga` code is from before the subprocess module was fully written. This means that the codebase has a number of different ways that it deals with system calls. Some of this is causing trouble as seen in #2104 . First point of this might be to modernise
 - [Shell.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/Utility/Shell.py)
 - [execute.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/Utility/execute.py)

### PR DESCRIPTION
**Pull request by shalearkane**
Partially Fixes #2105 
- remove timing code
- simplify getting output

### CODE REVIEW

**Comment by shalearkane** [comment]
@mesmith75 could you please review the changes and check if my approach is okay. I will then update the remaining files in the same manner.

**Comment by shalearkane** [comment]
@mesmith75  Also could you please give a hint about what this piece of code does:
https://github.com/ganga-devs/ganga/blob/99c18db0f7946e61522dce003b7d256c3a57e0cc/ganga/GangaCore/Utility/execute.py#L287-L299

As far my understanding, it runs the python code in `eval_includes`. We also pass the current local variables that are in the function. So does that mean that while refactoring, the local variables that were already present in the function should not be changed because that might break code that processes local variables (such as `stdout`) within `eval_includes`?

**Comment by egede** [comment]
> @mesmith75 Also could you please give a hint about what this piece of code does:
> 
> https://github.com/ganga-devs/ganga/blob/99c18db0f7946e61522dce003b7d256c3a57e0cc/ganga/GangaCore/Utility/execute.py#L287-L299
> 
> As far my understanding, it runs the python code in `eval_includes`. We also pass the current local variables that are in the function. So does that mean that while refactoring, the local variables that were already present in the function should not be changed because that might break code that processes local variables (such as `stdout`) within `eval_includes`?

I am not sure what it does, but it looks horribly complicated. I think a better approach is to trace down the places that the `execute` function is called and then for each of those understand what we actually try to do and if there is a simpler way to accomplish it.

**Comment by egede** [comment]
@shalearkane You want to do further work here within the next few days, or should we merge in the already very helpful changes?

**Comment by shalearkane** [comment]
I will create a new pull request for `execute.py` in a new PR. You can merge the current changes.

**Pull request closed without merging**
