### PR TITLE
Bugfix/ganga init transfer

### LINKED ISSUE #125: No Ganga/__init__.py shipped with job
Running the latest develop version, ```Ganga/Utilities/__init__.py``` and ```files.py``` are both shipped with the job, but no ```Ganga/__init__.py```, meaning that the job fails on the backend whenever attempting to load files relative to the _python/Ganga base directory (e.g. when adding an output sandbox).

### PR DESCRIPTION
**Pull request by drmarkwslater**
This fixes #125 by basically removing the whole mechanism and just sending the 'files.py' file and referencing it appropriately. This **may** bite us in the future as we can no longer 'easily' send Ganga modules with jobs. However, users can't do this anyway and we've gone this far without needing to send any more so I think it's worth the risk :)

### CODE REVIEW

**Comment by milliams** [comment]
retest this please

**Comment by milliams** [comment]
While I am in general in favour of merging this I think we should wait until we have sorted out the other issues we're working on at the moment. I would also want to run some manual LCG/Dirac tests to make sure it's still working there, Do people agree?

**Comment by drmarkwslater** [comment]
That sounds like a good idea to me - let's make sure the new tests are working and private testing is going well, etc. first.

**Comment by drmarkwslater** [comment]
retest this please

**Comment by drmarkwslater** [comment]
Any problems with merging this?

**Comment by milliams** [comment]
Since we don't yet have any automatic tests for remote jobs (LCG or Dirac) I'd like to make sure that this hasn't broken anything there. Apart from that, I'm happy.

**Comment by drmarkwslater** [comment]
Just run a private test for both Condor and LCG and both worked without issue. OK to merge?

**Comment by rob-c** [comment]
I don't think we make use of any of this in Dirac so go from me

**Comment by alexanderrichards** [comment]
:+1:

**Comment by milliams** [comment]
:+1:

**Pull request merged**
