### PR TITLE
New bender

### PR DESCRIPTION
**Pull request by VladimirRomanovsky**
Two new applications were added with minor changes with respect to previous PR.

### CODE REVIEW

**Comment by alexanderrichards** [comment]
test this please

**Comment by rob-c** [comment]
@milliams Can you take a look at why this is failing?

**Comment by alexanderrichards** [comment]
looks like a file system problem maybe?

**Comment by alexanderrichards** [comment]
retest this please

**Comment by alexanderrichards** [comment]
Tests passing and only two new files added so shouldn't be any problems/ interference with other stuff. I'll merge this in 5 mins then unless someone shouts :wink:

**Comment by alexanderrichards** [comment]
@VladimirRomanovsky was there an issue that this PR should be associated with?

**Comment by egede** [comment]
@alexanderrichards No related issue.

**Pull request merged**
