### PR TITLE
fix broken import

### PR DESCRIPTION
**Pull request by mjmottram**

### CODE REVIEW

**Comment by drmarkwslater** [comment]
Apologies - I missed that one! 👍  However, I'll wait until the release is out before merging to develop.

**Comment by drmarkwslater** [comment]
Just notices this was against `master` rather than `develop!! @milliams  - is this a problem?

**Comment by milliams** [comment]
It's not the end of the world. It won't be available to us until the next release but nothing should break.

**Comment by rob-c** [comment]
resyncing the branch isn't difficult, this would just be another PR to merge the changes from master and then carry on (frankly it could/should even be done manually with a single command)

**Pull request merged**
