### PR TITLE
Release notes 7.1.1

### PR DESCRIPTION
**Pull request by mesmith75**

### CODE REVIEW

**Comment by mesmith75** [comment]
test this please

**Comment by alexanderrichards** [comment]
look like failure to get files, hence write files to /tmp. Lets re-run the testing

**Comment by alexanderrichards** [comment]
just tried re-building. maybe we are low on space?

**Comment by mesmith75** [comment]
Could someone approve this please?

**Review by alexanderrichards — APPROVED** [review]

**Comment by alexanderrichards** [comment]
@mesmith75 the tests started working again. Do you know what the issue was?

**Comment by rob-c** [comment]
@alexanderrichards see the conversation on #1313

**Pull request merged**
