### PR TITLE
Use IPython 5

### LINKED ISSUE #1222: Outdated requirements
In our setup.py we require some ancient versions of things - in particular I note ipython 1.2.1 . We should update or get rid of the version specific requirements altogether.

### PR DESCRIPTION
**Pull request by mesmith75**
Fixes #1222 

Updates to IPython 5.X , with the requisite adjustments.

### CODE REVIEW

**Comment by rob-c** [comment]
How does the IPython5 history play with AFS is it known?
Also, is the user history forward accessible after the update?

**Comment by mesmith75** [comment]
@rob-c Not sure, although I don't think the second point really matters. Ill try out a fresh installation and see what happens.

This now has the necessary updates for the shell things. With regard the tests, I think we just need to install some extra packages on the machine.

**Comment by rob-c** [comment]
@mesmith75 I'd argue having the command history for how you submitted the job is very important, I know a lot of users who archive jobs out of ganga due to the poor performance of the XML repo who use the command history as a powerful tool to know what's going on.
This shouldn't be a painful thing to test as per moving from 0.17 to 1.x but I think if there are steps we need to take to preserve this it should be done.

**Comment by mesmith75** [comment]
test this

**Comment by mesmith75** [comment]
Sounds a bit odd but fine I guess. Often we find that the ipython history is corrupted and has to be removed anyway.

More importantly this is incompatible with the existing CVMFS (and AFS) installations. Once this has been released the old versions will no longer work.

**Comment by rob-c** [comment]
Ah yes the whole AFS multiple session issue.
This is only something hit by a small number of users as most users on lxplus still strictly run only 1 session at a time.

If you're going for a blank slate approach I would make this very clear to users in the release notes if the history is not going to be migrated as there is no way of getting the binary data out of the existing. Last time I forward migrated the history once on first launch in a one shot approach and that caused enough emails on the dast list and elsewhere about commands not being available from the history.

**Comment by mesmith75** [comment]
A quick installation suggests that the old history is maintained ok.

**Review by egede — COMMENTED** [review]
We still use the externals area on afs for eventually creating the release on /cvmfs. I guess that means that we have to install IPython 5 there for this to work?

**Comment by mesmith75** [comment]
@egede Yes - that should be taken care of by the install script used for the AFS and CVMFS installs when the release is done. I don't think we can have two versions together though so as I say previous versions of Ganga wouldn't work which is unfortunate.

**Comment by egede** [comment]
@mesmith75 There is version information in the install script, so I do think that we should be able to keep installation of past versions working as well.

However, it might be a better idea to kill the install script and move to pip instead. We could do that before we merge this?

**Comment by mesmith75** [comment]
@egede Ah, I didn't realise we could have two versions of ipython installed in the externals.

I agree it would be best just to move to pip and a virtualenv.

**Comment by mesmith75** [comment]
Now fixes #1235 too.

I think updating to absl-py doesn't require any changes from us.

**Comment by mesmith75** [comment]
The installation on CVMFS seems to be working fine - can I merge this?

**Review by egede — APPROVED** [review]
Has the code for installing in /cvmfs been updated as well? Where does that code reside?

**Comment by mesmith75** [comment]
@egede It has not. There is a script on the CVMFS machine but that never gets updated. I'll write a new one and get it to copy the version in the new release over itself so it will be updated.

**Pull request merged**
