### PR TITLE
Install udocker via pip

### PR DESCRIPTION
**Pull request by egede**

### CODE REVIEW

**Review by alexanderrichards — DISMISSED** [review]

**Review by joj0s — DISMISSED** [review]
Udocker installation works well for me with these new changes. So now the udocker installation unit tests can be removed as well I assume

**Comment by egede** [comment]
No unfortunately the test is about installing udocker inside Ganga (if a user is requesting to run their job in a container and docker is not installed). So the failing test is still relevant.

**Review by joj0s — DISMISSED** [review]

**Review by alexanderrichards — DISMISSED** [review]

**Comment by egede** [comment]
Argh, it seems like your reviews got dismissed when I merged the pep8 compliance PR.

**Review by alexanderrichards — APPROVED** [review]

**Comment by alexanderrichards** [comment]
Updated

**Pull request merged**
