### PR TITLE
Getting rid of bad warning when it's simply not needed

### PR DESCRIPTION
**Pull request by rob-c**
After or if the `GLITE_ENABLED` is set to false in the config there is no need to warn the user about missing files which will/should never be used.
Goes from:
```
INFO     LCG config is not set. Please set [LCG]VirtualOrganisation to your VO (e.g. "gridpp") or disable LCG with [LCG]GLITE_ENABLE=False
WARNING  Configuration of GLITE for LCG:
WARNING  File not found: /afs/cern.ch/sw/ganga/install/config/grid_env_auto.sh
```

```
INFO     LCG config is not set. Please set [LCG]VirtualOrganisation to your VO (e.g. "gridpp") or disable LCG with [LCG]GLITE_ENABLE=False
```

As long as we're not creating a proxy on systems when they start by default just because the tools are there I'm happy to wait until 6.1.22 for this to go in.

### CODE REVIEW

**Comment by rob-c** [comment]
As an aside should that default point to cvmfs now more then afs? I've no idea who uses GLITE but Im under the impression cvmfs is becoming the default?

**Comment by rob-c** [comment]
Any objections to squeezing this in as well before 6.1.21? It's just a small change which shouldn't effect users too much? (I only ask as #645 had to go in)

**Comment by milliams** [comment]
Sure, go for it :+1:

**Comment by rob-c** [comment]
ok, I'll wait for the tests to finish :+1:

**Pull request merged**
