### PR TITLE
Upload of patches from Jacek Holeczek for ND280

### PR DESCRIPTION
**Pull request by drmarkwslater**
Creating a PR for discussion of a load of GangaND280 changes from T2K

### CODE REVIEW

**Comment by milliams** [comment]
I'll review the code shortly but we should probably add a simple test to make sure that the code can be imported correctly etc. I guess we can't do much without the ND280 environment but a very simple test should be possible at least.

**Comment by alexanderrichards** [comment]
as a first pass this PR only touches code in the `GangaND280` package so should have no affect on the Ganga core or runtime. I agree however that we can do a simple import test

**Comment by drmarkwslater** [comment]
@JacekHoleczek is still waiting for some other possible code input so don't worry about it too much yet. The main problem for them is fixing #519 first.

I've asked for tests but they don't have any just yet. As you say though, a simple import test and maybe a couple of obvious Unit tests might be a good start.

**Comment by JacekHoleczek** [comment]
Two small notes:
1. the new source code contains some new files (apart from modifications to existing ones),
2, please remove "GangaND280.ini" from your git (it's been "renamed" into "ND280.ini", so that the new name of the ".ini" file follows the "standard" that I found in another subdirectories).

**Comment by drmarkwslater** [comment]
@JacekHoleczek Apologies - I missed a few things. Added them now!

**Comment by alexanderrichards** [comment]
looks like something has been merged under this branch as it's now out of date. Can you please rebase.

**Comment by alexanderrichards** [comment]
ah sorry mark, I though it was @JacekHoleczek who was proposing the PR.

**Comment by JacekHoleczek** [comment]
Could you, please, commit this new GangaND280 code into the current release, so that the new Ganga 6.1.21 source code contains it. I know, of course, that it will not work with the current release (due to the r'\n' problem, described elsewhere), but we could test this new GangaND280 with Ganga 6.0.4[34] (as already mentioned, we need to keep GnagaND280 backwards compatible).

**Comment by drmarkwslater** [comment]
I'll certainly merge this for 6.1.21 though I'll try to add some comments, etc. before then. Also, I think PR #543 should fix the `\n` problem 😄

**Comment by JacekHoleczek** [comment]
This "pull request" is hanging here for 10 days without being "incorporated" into the official Ganga source code.
In the meantime, I've got some new / modified files for GangaND280, so I would like to know how do you want me to proceed.

**Comment by drmarkwslater** [comment]
@JacekHoleczek I was just waiting until we were actually going to release 6.1.21 and then merge then because I might have got time to have a better look at the code and put in some changes (if needed) before the merge. So don't worry - this will **definitely** be in the 6.1.21 release! Having said that, if you want it in the develop branch earlier we can merge whenever you want.

If you have some changes to the code, best option is to fork this repo in your github account, apply the changes you want in a branch, then create a pull request against this repo from that (against the `develop` branch and we can review/merge it. Hopefully this page will help explain this better that I can:

https://help.github.com/articles/using-pull-requests/

Thanks!

**Comment by JacekHoleczek** [comment]
Could you then, please, "merge" this a bit "outdated" GangaND280 code (i.e. this "pull request") as it is.
I will then create my own "branch" and try to commit the newest modifications.

**Comment by drmarkwslater** [comment]
Will do - as soon as the tests have passed I'll merge this into develop and then you can do a PR from that.

**Comment by drmarkwslater** [comment]
All merged - please go ahead with the PR from your fork 😄

**Pull request merged**
