### PR TITLE
MassStorageFile will expand environment variables plus Slurm added to dictionaries plus GangaND280 fixes

### PR DESCRIPTION
**Pull request by JacekHoleczek**

### CODE REVIEW

**Review by alexanderrichards — APPROVED** [review]
Looks ok.

**General comment:** I dislike monolithic PRs that fix multiple issues as they are notoriously hard to review. Or else some might want to cherry pick only part of them. In future please submit one PR for one fix.

**Comment by JacekHoleczek** [comment]
That's what I tried here: https://github.com/ganga-devs/ganga/pull/1421
But the system simply added my new patches to an already existing  "pull request".
So it seems to me that as long as there is something "not-merged" waiting ... everything will be glued together.

**Comment by alexanderrichards** [comment]
> But the system simply added my new patches to an already existing "pull request".
> So it seems to me that as long as there is something "not-merged" waiting ... everything will be glued together.

If you create a new branch from the develop branch and do any new development on that then they will be totally separate.

**Comment by alexanderrichards** [comment]
@ganga-devs/core Looks like the webhook worked fine on this PR

**Comment by mesmith75** [comment]
@alexanderrichards Not quite - I triggered it. Also the testing isn't picking up the branch - the tests are only running on the PR.

**Comment by alexanderrichards** [comment]
@mesmith75 This is to be expected since the branch is in @JacekHoleczek own fork so we have no control of it. With this PR it's only the merge tests that we care about anyway.

**Comment by alexanderrichards** [comment]
thanks for letting me know you triggered it. I'll have to investigate further.

**Comment by JacekHoleczek** [comment]
For me the additional problem is that when I click the "New pull request" button, I don't have any way to exclude some of my own patches (so I cannot "split" it into several "independent" / "unrelated" requests / issues). It seems that the system takes everything that is new (at the moment I click the button) and glues it into a single request.

**Comment by alexanderrichards** [comment]
the "New Pull Request" button will make a PR from your branch. If you have patches on your branch that you don't want as part of the PR then consider not committing them to the branch but stashing them so you can reapply them back to the master once your branch is merged.

**Pull request merged**
