### PR TITLE
cli

### PR DESCRIPTION
**Pull request by gurudattapatil**

### CODE REVIEW

**Comment by gurudattapatil** [comment]
To use this use shell in bin/gui-terminal
Currently terminal runs on 127.0.0.1:11000, but working on configuring it to make it run on free port

**Review by egede — COMMENTED** [review]
We requested a few more changes last Monday. Are the coming in?

**Comment by gurudattapatil** [comment]
yes half of it is done, facing issue adding extra argument to the command, don't know exactly where the error is coming from.

**Comment by gurudattapatil** [comment]
@egede Developed the whole thing, command would be like this 
`ganga-gui-terminal --port=13000 --flask=18000 --internal-port=24000`
The height of the terminal can be changed from [here](https://github.com/ganga-devs/ganga/blob/8e0c77443bea38d1549b1da4aab86c74d5c3166f/ganga/GangaGUI/gui/templates/cli1.html#L24)

**Comment by gurudattapatil** [comment]
Will add the documentation this week

**Pull request closed without merging**
