### PR TITLE
Atlas exe use athena setup

### PR DESCRIPTION
**Pull request by drmarkwslater**
This PR fixes some issues of `--useAthenaPackages` not working correctly for EXE jobs. It also adds a quick fix to very recent versions of Athena changing how to assign input files. In addition, the `--useAthenaPackages` option has been made the default and deprecated with an option added (`--noUserPackageSetup`) to disable as requested by Will Buttinger.

### CODE REVIEW

**Review by mesmith75 — APPROVED** [review]

**Comment by mesmith75** [comment]
@drmarkwslater Are these non-python files being wanted in the released version? If so it might be worth checking they are there.

**Comment by drmarkwslater** [comment]
@mesmith75 Not sure what you mean by 'non-python files'? Do you mean the `athena` script? This is a python file, just not a `.py` file. It means you can run Ganga from the command line with:
```
ganga athena ...
```

**Comment by mesmith75** [comment]
@drmarkwslater Yes, I mean files without the `.py` suffix. I am not sure if they are being picked up at the moment.

**Comment by drmarkwslater** [comment]
@mesmith75 It has been up to this point so I'm assuming it's all OK 😄

**Comment by mesmith75** [comment]
@drmarkwslater Can we merge this?

**Comment by drmarkwslater** [comment]
@mesmith75 Not yet - after discussions with the users, they want to change the default behaviour and so I'll try to get this done today/tomorrow.

**Pull request merged**
