### PR TITLE
Fixing use of flush commands...

### PR DESCRIPTION
**Pull request by rob-c**
I'm assuming we want to standardize on flush_all in this case, but either way this line is broken

### CODE REVIEW

**Comment by rob-c** [comment]
I'm just going to merge as this is obviously little more than a typo

**Comment by milliams** [comment]
Yes, I have made this change to mine locally but hadn't pushed it yet. I think that happened because @drmarkwslater copied those two lines from your PR to his.

**Comment by rob-c** [comment]
I think this is because the default behavior at some point have repo._dict() not do what it was expected to do (flush all dirty). Given we're standardizing on flush_all being a wrapper for this I'm happy enough to go with what is being changed here.

**Comment by drmarkwslater** [comment]
Oops - Good catch @rob-c ! I did just blindly copy this :unamused:

**Pull request merged**
