### PR TITLE
iteritems() -> items() (python3) in  InteractiveScriptTemplate.py.template

### PR DESCRIPTION
**Pull request by admorris**

### CODE REVIEW

**Comment by mesmith75** [comment]
I am not sure this is the fix we want. The other scripts are explicitly python2 (`#!/usr/bin/env python2`) - do we want to do that instead to bring this into line with the others?

I guess ultimately we need to make the scripts python 2 and 3 compatible but perhaps that is for #1598

**Review by egede — DISMISSED** [review]

**Comment by alexanderrichards** [comment]
I thought we were keeping the run scripts python 2 compatible (although I forget now the reason for this). This change however doesn't break Python 2 compatibility merely makes it less efficient. I don't think this is necessary therefore but if we are maintaining Python 2 for the scripts then I think being explicit `#!/usr/bin/env python2` should be done.

**Comment by egede** [comment]
I think the optimal is if we can keep these scripts agnostic to python 2/3. The scripts are executed on remote nodes where we do not really have control over the python environment. So we can be in both the situation that we run on a plain centos7 system with only python2 available and on a system where python2 by default is no longer available (like Fedora 32).

**Comment by mesmith75** [comment]
Ok, let's merge this then as it is a minimal change that works for both.

We should probably put some priority into sorting the other scripts.

**Comment by mesmith75** [comment]
Does anyone remember how to get external branches to pass the tests?

**Comment by alexanderrichards** [comment]
> Does anyone remember how to get external branches to pass the tests?

you need to merge it into a new local branch and then have that one target develop

**Comment by mesmith75** [comment]
Ah, OK, I've replicated this in #1789 . I'll close this then.

**Pull request closed without merging**
