### PR TITLE
Ganga Tutorial Revived

### LINKED ISSUE #1566: Revive GangaTutorial package
The GangaTutorial package is not working in the latest release.

```
export GangaTutorial/Tutorial.ini`
(ganga) (base) [desktop] ~/programming/ganga % bin/ganga

*** Welcome to Ganga ***
Version: 8.2.0 - DEV
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


INFO     reading config file /home/egede/.gangarc
INFO     reading config file /home/egede/programming/ganga/src/ganga/ganga/GangaTutorial/Tutorial.ini
ERROR    problems with loading Plugin /home/egede/programming/ganga/src/ganga/ganga/GangaTutorial
ERROR    Reason: No module named 'Lib'
PluginError: Failed to load plugin: /home/egede/programming/ganga/src/ganga/ganga/GangaTutorial. Ganga will now shutdown to prevent job corruption.
(consider --debug option for more information)
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown
```
Looking at https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaGaudi/PACKAGE.py and https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaGaudi/__init__.py should make it clear what changes are required. Inside package there might be further changes required to deal with python3.

### PR DESCRIPTION
**Pull request by varunbankar**
Aim to solve #1566 
The last PR related to this issue seemed stale hence thought to take up the issue.

### **Information Related to the PR:**

The problem related to this issue was way deeper than it seemed, following is the summary of all the changes that were made:

**__init__.py:**
Fixed the import issues here.

**Lib/__init__.py:**
Further fixed the import issues here.

**Lib/PrimeFactorizer.py:**
"PrimeFactorizer" Class gave errors as it needed to have `is_prepared` attribute and `prepare` and `unprepare` method to be used for `j.application`, necessary changes were made to the Class by taking reference from `Executable` Class. There were further small import errors, those were fixed.

**Lib/PrimeFactorizerSplitter.py:**
"PrimeFactorizerSplitter" Class while splitting gave wrong arguments to the subjobs as it inserted a float number instead of integer inside `https://primes.utm.edu/lists/small/millions/primes%d.zip`. This small bug was fixed.

**Lib/PrimeTableDataset.py:**
An import error was fixed and the `table_location` URL was replaced by `https://primes.utm.edu/lists/small/millions`, the prime number tables are pulled from `https://primes.utm.edu/`. Eg: https://primes.utm.edu/lists/small/millions/primes1.zip

**Lib/primes/prime_factor.py:**
This is the most important file as it is used as executable by the tutorial, this program was changed from python2 to python3 and a download function was created to download prime number tables from the above URL which are then extracted and read by the application.

**Lib/primes/primes.py:**
`check_prime_job` function was revived, this function shows the output of the PrimeFactorizer jobs. Check the screenshot below for reference.

**setup.py:**
`requests` module is required by the `prime_factor.py`, it was added to the "install_requires" section.

**GangaCore/test/GPI/TestGangaTutorial.py:**
Tests were created to test the functionality and working of the GangaTutorial. Tests needed `TUTDIR` to be exported to GPI in order to be used by the above functions. Jenkins CI was giving error when `@add_config` decorator was used to change `RUNTIME_PATH` to `GangaTutorial` as in order for tests to run `RUNTIME_PATH` needs to be set as `GangaTest`. Please refer (https://github.com/ganga-devs/ganga/pull/1615#issuecomment-600213167)

### Screenshots:

**Working of PrimeFactorizer (no subjobs):**
Screenshot 2020-03-15 at 11 43 03 PM

**Working of PrimeFactorizer with PrimeFactorizerSplitter (with subjobs):**
Screenshot 2020-03-15 at 11 49 36 PM

**Pytest Results:**
Screenshot 2020-03-17 at 7 17 41 PM

Please let me know if any further changes are required.

### CODE REVIEW

**Review by egede — DISMISSED** [review]
Great work. Many thanks.

**Comment by egede** [comment]
Something is going terribly wrong with the testing here. I give an extract from the CI below. Please take a look and see if you can understand (and subsequently fix).
```
==================================== ERRORS ====================================
____________________ ERROR at setup of test_ganga_tutorial _____________________

request = <SubRequest 'gpi' for <Function test_ganga_tutorial>>
wipe_gangadir = None

    @pytest.yield_fixture(scope='function')
    def gpi(request, wipe_gangadir):
        """
        Provide the ganga GPI and runtime to the test.
    
        This allows full Ganga integration tests. The GPI namespace is
        available via the ``ganga`` fixture argument or via an import of
        ``GangaCore.GPI`` inside the function as usual.
        """
        config_values = getattr(request._pyfuncitem._obj, '_config_values', {})
        config_values = [(k[0], k[1], v) for k, v in list(config_values.items())]  # Convert from dict to a list of tuples
    #    testLHCb = request.config.getoption("--testLHCb")
>       start_ganga(gangadir(request), extra_opts=config_values)

ganga/GangaCore/testlib/fixtures.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ganga/GangaCore/testlib/GangaUnitTest.py:158: in start_ganga
    GangaCore.Runtime._prog.bootstrap(interactive=False)
ganga/GangaCore/Runtime/bootstrap.py:908: in bootstrap
    loadPlugins(GangaCore.GPI)
ganga/GangaCore/Utility/Runtime.py:294: in loadPlugins
    raise err
ganga/GangaCore/Utility/Runtime.py:290: in loadPlugins
    r.bootstrap(env_dict)
ganga/GangaCore/Utility/Runtime.py:185: in bootstrap
    exec("import %s.BOOT" % self.name)
ganga/GangaTutorial/BOOT.py:10: in <module>
    from GangaTutorial.Lib.primes.primes import check_prime_job, split_prime_job
ganga/GangaTutorial/Lib/__init__.py:1: in <module>
    from .PrimeFactorizer import *
ganga/GangaTutorial/Lib/PrimeFactorizer.py:20: in <module>
    class PrimeFactorizer(IPrepareApp):
ganga/GangaCore/GPIDev/Base/Objects.py:688: in __init__
    this_schema.createDefaultConfig()
ganga/GangaCore/GPIDev/Schema/Schema.py:177: in createDefaultConfig
    config = GangaCore.Utility.Config.makeConfig(defaultConfigSectionName(_self_name), "default attribute values for %s objects" % _self_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'defaults_PrimeFactorizer'
docstring = 'default attribute values for PrimeFactorizer objects', kwds = {}

    def makeConfig(name, docstring, **kwds):
        """
        Create a config package and attach metadata to it. makeConfig() should be called once for each package.
        """
    
        if _after_bootstrap:
>           raise ConfigError('attempt to create a configuration section [%s] after bootstrap' % name)
E           GangaCore.Utility.Config.Config.ConfigError: ConfigError: attempt to create a configuration section [defaults_PrimeFactorizer] after bootstrap

ganga/GangaCore/Utility/Config/Config.py:186: ConfigError
---------------------------- Captured stdout setup -----------------------------
[0;0mINFO     Starting ganga[0;0m
[0;0mINFO     Parsing Command Line options[0;0m
[0;0mINFO     Parsing Configuration Options[0;0m

*** Welcome to Ganga ***
Version: 8.2.2 - DEV
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


[0;0mINFO     Initializing[0;0m
[0;0mINFO     Bootstrapping[0;0m
---------------------------- Captured stderr setup -----------------------------
[0;31mERROR    problems with bootstrapping /ganga/ganga/GangaTutorial -- ignored[0;0m
[0;31mERROR    Reason: ConfigError: attempt to create a configuration section [defaults_PrimeFactorizer] after bootstrap [0;0m
------------------------------ Captured log setup ------------------------------
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:83 Starting ganga
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:85 Parsing Command Line options
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:151 Parsing Configuration Options
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:154 Initializing
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:157 Bootstrapping
ERROR    GangaCore.GangaCore.Utility:Runtime.py:292 problems with bootstrapping /ganga/ganga/GangaTutorial -- ignored
ERROR    GangaCore.GangaCore.Utility:Runtime.py:293 Reason: ConfigError: attempt to create a configuration section [defaults_PrimeFactorizer] after bootstrap
________________ ERROR at setup of test_ganga_tutorial_subjobs _________________

request = <SubRequest 'gpi' for <Function test_ganga_tutorial_subjobs>>
wipe_gangadir = None

    @pytest.yield_fixture(scope='function')
    def gpi(request, wipe_gangadir):
        """
        Provide the ganga GPI and runtime to the test.
    
        This allows full Ganga integration tests. The GPI namespace is
        available via the ``ganga`` fixture argument or via an import of
        ``GangaCore.GPI`` inside the function as usual.
        """
        config_values = getattr(request._pyfuncitem._obj, '_config_values', {})
        config_values = [(k[0], k[1], v) for k, v in list(config_values.items())]  # Convert from dict to a list of tuples
    #    testLHCb = request.config.getoption("--testLHCb")
>       start_ganga(gangadir(request), extra_opts=config_values)

ganga/GangaCore/testlib/fixtures.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ganga/GangaCore/testlib/GangaUnitTest.py:152: in start_ganga
    GangaCore.Runtime._prog.configure()
ganga/GangaCore/Runtime/bootstrap.py:781: in configure
    config_files = self.get_config_files(self.options.config_file)
ganga/GangaCore/Runtime/bootstrap.py:691: in get_config_files
    syscfg.setSessionValue('GANGA_CONFIG_PATH', config_path)
ganga/GangaCore/Utility/Config/Config.py:606: in setSessionValue
    value = h[0](name, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'GANGA_CONFIG_PATH', x = ''

    def deny_modification(name, x):
        raise GangaCore.Utility.Config.ConfigError(
>           'Cannot modify [System] settings (attempted %s=%s)' % (name, x))
E       GangaCore.Utility.Config.Config.ConfigError: ConfigError: Cannot modify [System] settings (attempted GANGA_CONFIG_PATH=)

ganga/GangaCore/Runtime/bootstrap.py:795: ConfigError
---------------------------- Captured stdout setup -----------------------------
[0;0mINFO     Starting ganga[0;0m
[0;0mINFO     Parsing Command Line options[0;0m
[0;0mINFO     Parsing Configuration Options[0;0m

*** Welcome to Ganga ***
Version: 8.2.2 - DEV
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


------------------------------ Captured log setup ------------------------------
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:83 Starting ganga
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:85 Parsing Command Line options
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:151 Parsing Configuration Options
______________________ ERROR at setup of test_job_create _______________________

request = <SubRequest 'gpi' for <Function test_job_create>>
wipe_gangadir = None

    @pytest.yield_fixture(scope='function')
    def gpi(request, wipe_gangadir):
        """
        Provide the ganga GPI and runtime to the test.
    
        This allows full Ganga integration tests. The GPI namespace is
        available via the ``ganga`` fixture argument or via an import of
        ``GangaCore.GPI`` inside the function as usual.
        """
        config_values = getattr(request._pyfuncitem._obj, '_config_values', {})
        config_values = [(k[0], k[1], v) for k, v in list(config_values.items())]  # Convert from dict to a list of tuples
    #    testLHCb = request.config.getoption("--testLHCb")
>       start_ganga(gangadir(request), extra_opts=config_values)

ganga/GangaCore/testlib/fixtures.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ganga/GangaCore/testlib/GangaUnitTest.py:152: in start_ganga
    GangaCore.Runtime._prog.configure()
ganga/GangaCore/Runtime/bootstrap.py:781: in configure
    config_files = self.get_config_files(self.options.config_file)
ganga/GangaCore/Runtime/bootstrap.py:691: in get_config_files
    syscfg.setSessionValue('GANGA_CONFIG_PATH', config_path)
ganga/GangaCore/Utility/Config/Config.py:606: in setSessionValue
    value = h[0](name, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'GANGA_CONFIG_PATH', x = ''

    def deny_modification(name, x):
        raise GangaCore.Utility.Config.ConfigError(
>           'Cannot modify [System] settings (attempted %s=%s)' % (name, x))
E       GangaCore.Utility.Config.Config.ConfigError: ConfigError: Cannot modify [System] settings (attempted GANGA_CONFIG_PATH=)

ganga/GangaCore/Runtime/bootstrap.py:795: ConfigError
---------------------------- Captured stdout setup -----------------------------
[0;0mINFO     Starting ganga[0;0m
[0;0mINFO     Parsing Command Line options[0;0m
[0;0mINFO     Parsing Configuration Options[0;0m

*** Welcome to Ganga ***
Version: 8.2.2 - DEV
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


------------------------------ Captured log setup ------------------------------
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:83 Starting ganga
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:85 Parsing Command Line options
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:151 Parsing Configuration Options
_______________________ ERROR at setup of test_job_kill ________________________

request = <SubRequest 'gpi' for <Function test_job_kill>>, wipe_gangadir = None

    @pytest.yield_fixture(scope='function')
    def gpi(request, wipe_gangadir):
        """
        Provide the ganga GPI and runtime to the test.
    
        This allows full Ganga integration tests. The GPI namespace is
        available via the ``ganga`` fixture argument or via an import of
        ``GangaCore.GPI`` inside the function as usual.
        """
        config_values = getattr(request._pyfuncitem._obj, '_config_values', {})
        config_values = [(k[0], k[1], v) for k, v in list(config_values.items())]  # Convert from dict to a list of tuples
    #    testLHCb = request.config.getoption("--testLHCb")
>       start_ganga(gangadir(request), extra_opts=config_values)

ganga/GangaCore/testlib/fixtures.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ganga/GangaCore/testlib/GangaUnitTest.py:152: in start_ganga
    GangaCore.Runtime._prog.configure()
ganga/GangaCore/Runtime/bootstrap.py:781: in configure
    config_files = self.get_config_files(self.options.config_file)
ganga/GangaCore/Runtime/bootstrap.py:691: in get_config_files
    syscfg.setSessionValue('GANGA_CONFIG_PATH', config_path)
ganga/GangaCore/Utility/Config/Config.py:606: in setSessionValue
    value = h[0](name, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'GANGA_CONFIG_PATH', x = ''

    def deny_modification(name, x):
        raise GangaCore.Utility.Config.ConfigError(
>           'Cannot modify [System] settings (attempted %s=%s)' % (name, x))
E       GangaCore.Utility.Config.Config.ConfigError: ConfigError: Cannot modify [System] settings (attempted GANGA_CONFIG_PATH=)

ganga/GangaCore/Runtime/bootstrap.py:795: ConfigError
---------------------------- Captured stdout setup -----------------------------
[0;0mINFO     Starting ganga[0;0m
[0;0mINFO     Parsing Command Line options[0;0m
[0;0mINFO     Parsing Configuration Options[0;0m

*** Welcome to Ganga ***
Version: 8.2.2 - DEV
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


------------------------------ Captured log setup ------------------------------
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:83 Starting ganga
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:85 Parsing Command Line options
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:151 Parsing Configuration Options
______________________ ERROR at setup of test_job_submit _______________________

request = <SubRequest 'gpi' for <Function test_job_submit>>
wipe_gangadir = None

    @pytest.yield_fixture(scope='function')
    def gpi(request, wipe_gangadir):
        """
        Provide the ganga GPI and runtime to the test.
    
        This allows full Ganga integration tests. The GPI namespace is
        available via the ``ganga`` fixture argument or via an import of
        ``GangaCore.GPI`` inside the function as usual.
        """
        config_values = getattr(request._pyfuncitem._obj, '_config_values', {})
        config_values = [(k[0], k[1], v) for k, v in list(config_values.items())]  # Convert from dict to a list of tuples
    #    testLHCb = request.config.getoption("--testLHCb")
>       start_ganga(gangadir(request), extra_opts=config_values)

ganga/GangaCore/testlib/fixtures.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ganga/GangaCore/testlib/GangaUnitTest.py:152: in start_ganga
    GangaCore.Runtime._prog.configure()
ganga/GangaCore/Runtime/bootstrap.py:781: in configure
    config_files = self.get_config_files(self.options.config_file)
ganga/GangaCore/Runtime/bootstrap.py:691: in get_config_files
    syscfg.setSessionValue('GANGA_CONFIG_PATH', config_path)
ganga/GangaCore/Utility/Config/Config.py:606: in setSessionValue
    value = h[0](name, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'GANGA_CONFIG_PATH', x = ''

    def deny_modification(name, x):
        raise GangaCore.Utility.Config.ConfigError(
>           'Cannot modify [System] settings (attempted %s=%s)' % (name, x))
E       GangaCore.Utility.Config.Config.ConfigError: ConfigError: Cannot modify [System] settings (attempted GANGA_CONFIG_PATH=)

ganga/GangaCore/Runtime/bootstrap.py:795: ConfigError
---------------------------- Captured stdout setup -----------------------------
[0;0mINFO     Starting ganga[0;0m
[0;0mINFO     Parsing Command Line options[0;0m
[0;0mINFO     Parsing Configuration Options[0;0m

*** Welcome to Ganga ***
Version: 8.2.2 - DEV
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


------------------------------ Captured log setup ------------------------------
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:83 Starting ganga
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:85 Parsing Command Line options
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:151 Parsing Configuration Options
_____________________ ERROR at setup of test_job_completed _____________________

request = <SubRequest 'gpi' for <Function test_job_completed>>
wipe_gangadir = None

    @pytest.yield_fixture(scope='function')
    def gpi(request, wipe_gangadir):
        """
        Provide the ganga GPI and runtime to the test.
    
        This allows full Ganga integration tests. The GPI namespace is
        available via the ``ganga`` fixture argument or via an import of
        ``GangaCore.GPI`` inside the function as usual.
        """
        config_values = getattr(request._pyfuncitem._obj, '_config_values', {})
        config_values = [(k[0], k[1], v) for k, v in list(config_values.items())]  # Convert from dict to a list of tuples
    #    testLHCb = request.config.getoption("--testLHCb")
>       start_ganga(gangadir(request), extra_opts=config_values)

ganga/GangaCore/testlib/fixtures.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ganga/GangaCore/testlib/GangaUnitTest.py:152: in start_ganga
    GangaCore.Runtime._prog.configure()
ganga/GangaCore/Runtime/bootstrap.py:781: in configure
    config_files = self.get_config_files(self.options.config_file)
ganga/GangaCore/Runtime/bootstrap.py:691: in get_config_files
    syscfg.setSessionValue('GANGA_CONFIG_PATH', config_path)
ganga/GangaCore/Utility/Config/Config.py:606: in setSessionValue
    value = h[0](name, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'GANGA_CONFIG_PATH', x = ''

    def deny_modification(name, x):
        raise GangaCore.Utility.Config.ConfigError(
>           'Cannot modify [System] settings (attempted %s=%s)' % (name, x))
E       GangaCore.Utility.Config.Config.ConfigError: ConfigError: Cannot modify [System] settings (attempted GANGA_CONFIG_PATH=)

ganga/GangaCore/Runtime/bootstrap.py:795: ConfigError
---------------------------- Captured stdout setup -----------------------------
[0;0mINFO     Starting ganga[0;0m
[0;0mINFO     Parsing Command Line options[0;0m
[0;0mINFO     Parsing Configuration Options[0;0m

*** Welcome to Ganga ***
Version: 8.2.2 - DEV
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


------------------------------ Captured log setup ------------------------------
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:83 Starting ganga
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:85 Parsing Command Line options
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:151 Parsing Configuration Options
____________________ ERROR at setup of test_job_assignment _____________________

request = <SubRequest 'gpi' for <Function test_job_assignment>>
wipe_gangadir = None

    @pytest.yield_fixture(scope='function')
    def gpi(request, wipe_gangadir):
        """
        Provide the ganga GPI and runtime to the test.
    
        This allows full Ganga integration tests. The GPI namespace is
        available via the ``ganga`` fixture argument or via an import of
        ``GangaCore.GPI`` inside the function as usual.
        """
        config_values = getattr(request._pyfuncitem._obj, '_config_values', {})
        config_values = [(k[0], k[1], v) for k, v in list(config_values.items())]  # Convert from dict to a list of tuples
    #    testLHCb = request.config.getoption("--testLHCb")
>       start_ganga(gangadir(request), extra_opts=config_values)

ganga/GangaCore/testlib/fixtures.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ganga/GangaCore/testlib/GangaUnitTest.py:152: in start_ganga
    GangaCore.Runtime._prog.configure()
ganga/GangaCore/Runtime/bootstrap.py:781: in configure
    config_files = self.get_config_files(self.options.config_file)
ganga/GangaCore/Runtime/bootstrap.py:691: in get_config_files
    syscfg.setSessionValue('GANGA_CONFIG_PATH', config_path)
ganga/GangaCore/Utility/Config/Config.py:606: in setSessionValue
    value = h[0](name, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'GANGA_CONFIG_PATH', x = ''

    def deny_modification(name, x):
        raise GangaCore.Utility.Config.ConfigError(
>           'Cannot modify [System] settings (attempted %s=%s)' % (name, x))
E       GangaCore.Utility.Config.Config.ConfigError: ConfigError: Cannot modify [System] settings (attempted GANGA_CONFIG_PATH=)

ganga/GangaCore/Runtime/bootstrap.py:795: ConfigError
---------------------------- Captured stdout setup -----------------------------
[0;0mINFO     Starting ganga[0;0m
[0;0mINFO     Parsing Command Line options[0;0m
[0;0mINFO     Parsing Configuration Options[0;0m

*** Welcome to Ganga ***
Version: 8.2.2 - DEV
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


------------------------------ Captured log setup ------------------------------
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:83 Starting ganga
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:85 Parsing Command Line options
INFO     GangaCore.GangaCore.testlib:GangaUnitTest.py:151 Parsing Configuration Options
_______________________ ERROR at setup of test_job_copy ________________________

request = <SubRequest 'gpi' for <Function test_job_copy>>, wipe_gangadir = None

    @pytest.yield_fixture(scope='function')
    def gpi(request, wipe_gangadir):
        """
        Provide the ganga GPI and runtime to the test.
    
        This allows full Ganga integration tests. The GPI namespace is
        available via the ``ganga`` fixture argument or via an import of
        ``GangaCore.GPI`` inside the function as usual.
        """
        config_values = getattr(request._pyfuncitem._obj, '_config_values', {})
        config_values = [(k[0], k[1], v) for k, v in list(config_values.items())]  # Convert from dict to a list of tuples
    #    testLHCb = request.config.getoption("--testLHCb")
>       start_ganga(gangadir(request), extra_opts=config_values)

ganga/GangaCore/testlib/fixtures.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ganga/GangaCore/testlib/GangaUnitTest.py:152: in start_ganga
    GangaCore.Runtime._prog.configure()
ganga/GangaCore/Runtime/bootstrap.py:781: in configure
    config_files = self.get_config_files(self.options.config_file)
ganga/GangaCore/Runtime/bootstrap.py:691: in get_config_files
    syscfg.setSessionValue('GANGA_CONFIG_PATH', config_path)
ganga/GangaCore/Utility/Config/Config.py:606: in setSessionValue
    value = h[0](name, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'GANGA_CONFIG_PATH', x = ''

    def deny_modification(name, x):
        raise GangaCore.Utility.Config.ConfigError(
>           'Cannot modify [System] settings (attempted %s=%s)' % (name, x))
E       GangaCore.Utility.Config.Config.ConfigError: ConfigError: Cannot modify [System] settings (attempted GANGA_CONFIG_PATH=)

ganga/GangaCore/Runtime/bootstrap.py:795: ConfigError
---------------------------- Captured stdout setup -----------------------------
[0;0mINFO     Starting ganga[0;0m
[0;0mINFO     Parsing Command Line options[0;0m
[0;0mINFO     Parsing Configuration Options[0;0m

*** Welcome to Ganga ***
Version: 8.2.2 - DEV
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.

```

**Comment by varunbankar** [comment]
The Tests were causing the problem (as GANGA_CONFIG_PATH is needed to change for the tests to run), but worked fine on my machine. The functionality of GangaTutorial is fine and working only. I'll look into this test issue and send another PR for the tests, if that is fine.

**Comment by egede** [comment]
OK, let me know if you need help. It was essentially *all* tests that were failing, so something went horribly wrong!

**Comment by varunbankar** [comment]
After extensive digging into the tests and writing the same tests in 5 different ways, the probable explanation for Jenkins CI failing can be that the previous tests set the `RUNTIME_PATH` configuration value to `GangaTutorial` but in order for tests to run it needs to be set to `GangaTest` which caused conflict and all the tests after `TestGangaTutorial.py` failed. The tests were rewritten in order to avoid this conflict and GangaTutorial functionality along with the tests are working completely fine now. 

The reference to those 4 failed tests written in different ways, for documentation purposes can be found at #1618 (This PR was specifically created for testing purpose as the tests were passing in my development environment and failed in Jenkins CI). That PR is closed now.

**Review by egede — APPROVED** [review]

**Pull request merged**
