### PR TITLE
Fix xml processing

### PR DESCRIPTION
**Pull request by mesmith75**
Added the LHCb XML processing code to ganga and converted to python3

### CODE REVIEW

**Review by egede — APPROVED** [review]
Does this mean that the code should be deleted from some other project?

**Comment by mesmith75** [comment]
No I don't think so. I just took this from LHCb/Kernel which is where the applications would look for it.

**Comment by alexpearce** [comment]
I'm working on the Python 3 port of LHCb in [LHCb!2214](https://gitlab.cern.ch/lhcb/LHCb/merge_requests/2214); it would be great to have a patch for the `XMLSummarySvc` there!

(I've seen problems with it locally, but haven't had the time to patch it yet.)

**Comment by egede** [comment]
@alexpearce Looking at the files changed for the PR should give you what you want!

**Pull request merged**
