### PR TITLE
Initial attempt at fixing vanilla Dirac exe

### PR DESCRIPTION
**Pull request by rob-c**
This is a first attempt to address #1282.

I've not tested this with any other application other than Executable and so don't know if any other RTHandlers are impacted (I suspect not).

Hopefully this fixes everything as I was able to submit a correct looking JDL with this but haven't tested if the job runs/completes/etc.

### CODE REVIEW

**Review by egede — APPROVED** [review]

**Comment by rob-c** [comment]
Suppose I should submit some LHCb  test jobs with this to check it doesn't break things in new and exciting ways, if someone else tests this and it works feel free to merge from me :smile:

**Comment by mesmith75** [comment]
test this please

**Comment by mesmith75** [comment]
No, this has broken it. Now DiracFiles in inputfiles are not included at all.

**Comment by mesmith75** [comment]
@rob-c I apologise, I was wrong. This does indeed work fine for executable jobs. There is an issue with GaudiExec not including DiracFiles which I think I have found the source of. Let's merge this and I'll fix that in a separate PR.

**Pull request merged**
