### PR TITLE
Cleanup GangaRelease/tools

### LINKED ISSUE #2114: Cleanup GangaRelease/tools
The directory [GangaRelease/tools](https://github.com/ganga-devs/ganga/tree/develop/ganga/GangaRelease/tools) is full of files that are no longer used. It should be identified which files (if any) we still use and the rest deleted.

### PR DESCRIPTION
**Pull request by shalearkane**
Fixes #2114

### CODE REVIEW

**Comment by abhijeetsharma200** [comment]
@egede, it seems that we are facing the same X509 certificate error. What steps can we take to resolve this issue and ensure that it does not cause any further PR failures?

**Comment by egede** [comment]
> @egede, it seems that we are facing the same X509 certificate error. What steps can we take to resolve this issue and ensure that it does not cause any further PR failures?

The issue is that some of the tests depend on a X509 certificate. We can't allow this certificate to have world wide readability so there is no "solution" to this.

**Comment by abhijeetsharma200** [comment]
> > @egede, it seems that we are facing the same X509 certificate error. What steps can we take to resolve this issue and ensure that it does not cause any further PR failures?
> 
> The issue is that some of the tests depend on a X509 certificate. We can't allow this certificate to have world wide readability so there is no "solution" to this.

I see thanks for your response.

**Review by egede — APPROVED** [review]

**Comment by egede** [comment]
@shalearkane All good. Will be merged now.

**Pull request merged**
