### PR TITLE
6.3 features

### PR DESCRIPTION
**Pull request by rob-c**
This PR is a collection of all of the things which have gone into the `6.3-features` branch over `develop`.

The main changes are (broadly):
(please feel free to edit if more features get merged into the branch)
1. Adding `copyTo` (internal) and changing the `get` methods for all `IGangaFile` Objects
2. Renamed the template script files to fix problems with code checker
3. Better handling of Dirac errors within Ganga added `GangaDiracError`
4. Added support for `SharedFile`
5. Cleaned up code for handling of file locks
6. Initial implementation of new credentials system for LCG/Dirac
7. tbd...

I'm not looking to merge this PR I'm just opening this so that I can update this branch with the changes from develop and make sure that the code merge for 6.3.0 is hopefully pain free.

### CODE REVIEW

**Comment by milliams** [comment]
Just a note for when this PR is finally merged into `develop` before release: Can we be very careful that is is merged as either a *Create a merge commit* or, better still, *Rebase and merge* to ensure that the individual commits in this branch are not lost.

**Comment by mesmith75** [comment]
Is this branch currently working? I am trying to do a simple bookkeeping query and get a problem with the GangaDiracError:
```python
Ganga In [1]: data = BKQuery('/LHCb/Collision12/Beam4000GeV-VeloClosed-MagDown/Real Data/Reco14/Stripping21/90000000/SEMILEPTONIC.DST').getDataset()
ERROR    Error: global name 'GangaDiracError' is not defined
ERROR    !!Unknown/Unexpected ERROR!!
ERROR    If you're able to reproduce this please report this to the Ganga developers!
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/python/Ganga/GPI/__init__.pyc in <module>()
----> 1 data = BKQuery('/LHCb/Collision12/Beam4000GeV-VeloClosed-MagDown/Real Data/Reco14/Stripping21/90000000/SEMILEPTONIC.DST').getDataset()

/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/python/Ganga/GPIDev/Base/Proxy.pyc in proxy_wrapped(*args, **kwargs)
    689         s_args = [stripProxy(a) for a in args]
    690         s_kwargs = dict((name, stripProxy(a)) for name, a in kwargs.items())
--> 691         r = f(*s_args, **s_kwargs)
    692         return addProxy(r)
    693 

/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/python/GangaLHCb/Lib/LHCbDataset/BKQuery.pyc in getDataset(self)
    160             cmd = "getDataset('%s',%s,'%s','%s','%s','%s')" % (self.path, self.dqflag, self.type, self.startDate,
    161                                                                self.endDate, self.selection)
--> 162         result = get_result(cmd, 'BK query error.')
    163 
    164         logger.debug("Finished Running Command")

/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/python/GangaDirac/Lib/Backends/DiracUtils.py in get_result(command, exception_message, eval_includes, retry_limit)
     32         try:
     33             return execute(command, eval_includes=eval_includes)
---> 34         except GangaDiracError as err:
     35             logger.error(exception_message)
     36             logger.debug("Sleeping for 5 additional seconds to reduce possible overloading")

NameError: global name 'GangaDiracError' is not defined
```

**Comment by rob-c** [comment]
@mesmith75 Can you open an issue that we don't have any form of test which currently tests the BookKeeping functions correctly for LHCb(Dirac?) as this has broken in this PR and nothing has picked this up. I'm looking at the GaudiExec tests today/tomorrow so I'll see if I can add one there.
Also, can you review the changes I'm looking in to help LHCb users with the new credentials branch #825 .

**Comment by rob-c** [comment]
@mesmith75 FYI I get the following error when I try to execute the command you give above (after fixing the ganga problem you see):
```
("Cannot get URL for Bookkeeping/BookkeepingManager in setup LHCb-Production: RuntimeError('Option /DIRAC/Setups/LHCb-Production/Bookkeeping is not defined',)"
```
I don't know if this could be caused by a bug in the latest LHCbDirac or whether the request is bad atm

**Comment by rob-c** [comment]
actually that's now working fine in #825 with the latest LHCbDirac I think there was a transient server configuration issue

**Comment by mesmith75** [comment]
@rob-c Thanks - I'll test out the other PR.

**Comment by rob-c** [comment]
Now in 6.3 there's no way of checking if the `LCG` subsystem is enabled are not. This means the classes will crash tests under LHCb and there's no way to protect against this.
I think this can be alleviated by making a decorator which tests for a valid certificate before running a test but this looks like it could be difficult.

**Comment by mesmith75** [comment]
6.2.3 is released now so we should look to merge this once the credential decorator is in. Is there anything else to be added to this branch now?

**Comment by rob-c** [comment]
The tests need fixing, but aside from this I'm not sure what needs doing (if anything) I'd need 30min to re-read through all of the changes and let you know.

**Comment by alexanderrichards** [comment]
the site configs use a separate env variable `GANGA_CONFIG_PATH`. The one in this patch is purely a replacement for the default user config file so an or is appropriate here i think.

**Comment by mesmith75** [comment]
If we are all happy we should merge this into develop.

**Comment by alexanderrichards** [comment]
:+1: assuming the tests all run fine

**Comment by alexanderrichards** [comment]
OK biting the bullet eek :worried:

**Pull request merged**
