### PR TITLE
Removing LHCbApp references in GaussSplitter

### PR DESCRIPTION
**Pull request by rob-c**
Removing LHCbApp references in GaussSplitter

Having this in the splitter causes problems. I'm removing it from 6.1.25 onwards as any bugs from not having this I would argue are user/application bugs.

### CODE REVIEW

**Comment by rob-c** [comment]
This needs to go into 6.1.25 or whatever the next version is as this effects LHCb users and makes MC generation impossible.

**Comment by drmarkwslater** [comment]
Assuming the `LHCbApp` reference isn't needed by other things, then 👍

**Comment by rob-c** [comment]
@drmarkwslater Yes it's not this needed elsewhere and has a very limited scope/use thankfully

**Comment by rob-c** [comment]
@mesmith75 any objections to merging?

**Comment by mesmith75** [comment]
@rob-c No objections if it works. I agree it needs to go into 6.1.25.

**Pull request merged**
