### PR TITLE
Add autopep8 PR creation to CI

### PR DESCRIPTION
**Pull request by joj0s**

### CODE REVIEW

**Comment by mesmith75** [comment]
If you are using autopep8 I think you need to set the max line length to match that in flake8 - I am not sure they are the same. Sorry if you already have and I missed it.

**Comment by joj0s** [comment]
According to [the docs](https://github.com/hhatto/autopep8#configuration), autopep8 should read the info about rules and line length from the flake8 section in our setup.cfg file.

**Comment by mesmith75** [comment]
ah very good

**Review by egede — APPROVED** [review]
Looks great.

**Review by mesmith75 — APPROVED** [review]

**Pull request merged**
