### PR TITLE
Replace get with CopyTo

### LINKED ISSUE #910: Error: get() got an unexpected keyword argument 'localPath'
Dear developers,

I'm getting the following error in ganga 6.3.0 when trying to retrieve the output of a job , it tells me to report it. 

Cheers, Rolf

```
Ganga In [7]: for sj in jobs(68).subjobs:

    sj.backend.getOutputData()

         ...:     

ERROR    Error: get() got an unexpected keyword argument 'localPath'

ERROR    !!Unknown/Unexpected ERROR!!

ERROR    If you're able to reproduce this please report this to the Ganga developers!

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v603r0/install/ganga/python/Ganga/GPI/__init__.py in <module>()

      1 for sj in jobs(68).subjobs:

----> 2     sj.backend.getOutputData()

      3 


/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v603r0/install/ganga/python/Ganga/GPIDev/Base/Proxy.py in proxy_wrapped(*args, **kwargs)

    689         s_args = [stripProxy(a) for a in args]

    690         s_kwargs = dict((name, stripProxy(a)) for name, a in kwargs.items())

--> 691         r = f(*s_args, **s_kwargs)

    692         return addProxy(r)

    693 


/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v603r0/install/ganga/python/GangaDirac/Lib/Backends/DiracBase.py in getOutputData(self, outputDir, names, force)

    481                 suceeded.extend([download(f, sj, True) for f in outputfiles_iterator(sj, DiracFile) if f.lfn != '' and (names is None or f.namePattern in names)])

    482         else:

--> 483             suceeded.extend([download(f, j, False) for f in outputfiles_iterator(j, DiracFile) if f.lfn != '' and (names is None or f.namePattern in names)])

    484 

    485         return filter(lambda x: x is not None, suceeded)


/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v603r0/install/ganga/python/GangaDirac/Lib/Backends/DiracBase.py in download(dirac_file, job, is_subjob)

    468             try:

    469                 if isType(dirac_file, DiracFile):

--> 470                     dirac_file.get(localPath=dirac_file.localDir)

    471                 else:

    472                     dirac_file.get()


TypeError: get() got an unexpected keyword argument 'localPath'


[13:29:45]

Ganga In [8]: 
```

### PR DESCRIPTION
**Pull request by mesmith75**
Fixes #910 .
The ```get ``` function got renamed at some point to internalCopyTo, which broke the getOutputData function in DiracBase.

I replaced get in the export methods with the new name.

### CODE REVIEW

**Comment by rob-c** [comment]
No, the internal method is internal, please don't use this. Just remove the argument to the method and set the localDir correctly in the file object before calling `get`

**Comment by mesmith75** [comment]
Ah I see - I see the point of IGangaFile now.

**Comment by rob-c** [comment]
@mesmith75 The large amount of work I did with fixing `get` should allow for this entire conditional check for `DiracFile` to be removed. Calling `get()` will get the file to `file.localDir` by construction which is what we expect.
There is no need to be passing information to the class that it already has.

**Comment by mesmith75** [comment]
Any objections to merging?

**Pull request merged**
