### PR TITLE
Execute initial GaudiExec make in correct environment

### LINKED ISSUE #1242: Different architecture/gcc version on submitting machine and server causes CMake failure
Having a different architecture on the host and on the server causes cmake to fail building as:

```
ERROR    Failed to execute command: /tmp/tmps0Q3Wy.sh
ERROR    Failed to execute command: /tmp/tmps0Q3Wy.sh
ERROR    Tried to execute command in: /disk/homedisk/home/nasf/git/rootless-broccoli/ntuple-maker/DaVinciDev_v39r1p1
ERROR    Tried to execute command in: /disk/homedisk/home/nasf/git/rootless-broccoli/ntuple-maker/DaVinciDev_v39r1p1
ERROR    StdErr: WARNING : using environment variable CMTSITE for cmtsite
WARNING : using environment variable User_release_area for userarea
WARNING : using environment variable VO_LHCB_SW_DIR for sharedarea
./run: line 21: ./build_env.sh: No such file or directory
ERROR    StdErr: WARNING : using environment variable CMTSITE for cmtsite
WARNING : using environment variable User_release_area for userarea
WARNING : using environment variable VO_LHCB_SW_DIR for sharedarea
./run: line 21: ./build_env.sh: No such file or directory
ERROR    GangaException: Failed to Execute command
ERROR    GangaException: Failed to Execute command
ERROR    GangaException: Failed to Execute command ... reverting job 299 to the new status
ERROR    GangaException: Failed to Execute command ... reverting job 299 to the new status
```

(Different versions as demonstrated using LHCb software stack:

```
[10:56:21]
Ganga In [13]: x.j.application
Ganga Out [13]:
 GaudiExec (
   getMetadata = False,
   extraArgs = []  ,
   is_prepared = None,
   extraOpts = ,
   useGaudiRun = True,
   platform = x86_64-slc6-gcc49-opt,
   directory = /disk/homedisk/home/nasf/git/rootless-broccoli/ntuple-maker/DaVinciDev_v39r1p1,
   options = [ LocalFile (
   namePattern = 'ntuple_maker_mc_12103091_2011.py',
   compressed = False,
   localDir = '/disk/homedisk/home/nasf/git/rootless-broccoli/ntuple-maker/tangled'
 )]
 )
[10:56:24]
Ganga In [14]: !echo $CMTCONFIG
x86_64-slc6-gcc62-opt
```
)

### PR DESCRIPTION
**Pull request by mesmith75**
Fixes #1242

### CODE REVIEW

**Comment by mesmith75** [comment]
Could someone review this please. People doing the starterkit are starting to complain.

**Comment by mesmith75** [comment]
Also update the default compiler to gcc62.

**Review by drmarkwslater — APPROVED** [review]
Makes sense to me though I'm wouldn't claim I was an expert on this code 😄

**Comment by mesmith75** [comment]
@drmarkwslater Thanks!

**Pull request merged**
