### PR TITLE
Fix incorrect arcsub command

### PR DESCRIPTION
**Pull request by datty**
Submission using ARC backend fails due to an incorrect submission interface being used in the arcsub command.

### CODE REVIEW

**Comment by milliams** [comment]
test this please

**Comment by alexanderrichards** [comment]
test this please

**Comment by drmarkwslater** [comment]
@datty Thanks very much for this! We missed this typo in a clean up of the Grid code recently. Will merge after the tests complete.

**Comment by drmarkwslater** [comment]
@datty Can you merge the latest changes into this branch please? Then I'll merge into Ganga's develop myself 😄

**Comment by datty** [comment]
I think I've done it, I've not really used git before so it's possible I've done it wrong. Thanks

**Comment by drmarkwslater** [comment]
@datty Great! I'll try to merge this as soon as the tests finish

**Comment by drmarkwslater** [comment]
@ganga-ci  retest this please

**Comment by drmarkwslater** [comment]
@datty Very sorry but we've had an issue with the tests and something else has been merged in the meantime. Would you be able to update to develop again? Again, very sorry!

**Comment by drmarkwslater** [comment]
@ganga-ci retest this please

**Comment by alexanderrichards** [comment]
Thanks for the contribution @datty

**Pull request merged**
