### PR TITLE
Fixing bug in opts parser for GaudiExec

### LINKED ISSUE #841: Bugfix readInputData in GaudiExec
I know there is not much appetite for keeping this feature but it seems like a lot of people still use it and I don't think it has been properly eradicated from the tutorials yet. At the moment is throwing up and error. I'll look into it.
```python
INFO     Started parsing input Data file
ERROR    PythonOptsCmakeParserError:
'GaudiExec' object has no attribute 'exec_cmd'                                                                                                                                      
ERROR    Error: ApplicationConfigurationError: Unable to parse the job options. Please check options files and extraopts. 

```

### PR DESCRIPTION
**Pull request by rob-c**
Fixes #841 
@mesmith75 Can you test this PR as this should fix the problems with `readInputData`.

### CODE REVIEW

**Comment by mesmith75** [comment]
@rob-c I'm afraid that hasn't fixed it. It gives a different error
```python
INFO     Started parsing input Data file
ERROR    Failed to execute command: /tmp/masmith/tmpW5SV5n.sh
ERROR    Tried to execute command in: /afs/cern.ch/work/m/masmith/GangaTest/test
ERROR    StdErr: WARNING : using environment variable CMTSITE for cmtsite
WARNING : using environment variable User_release_area for userarea
WARNING : using environment variable LHCBNIGHTLIES for nightlies_dir
/tmp/masmith/tmpW5SV5n.sh: line 2: gaudirun.py: command not found

ERROR    PythonOptsCmakeParserError:
GangaException:  ('Failed to Execute command',)
ERROR    Error: ApplicationConfigurationError: Unable to parse the job options. Please check options files and extraopts. 
```

Just running the ```python getGaudiExecInputData('/afs/cern.ch/user/m/masmith/private/year-4/VELO/2010/collision10.py', j.application) ``` gives an odd error
```python
Ganga In [3]: getGaudiExecInputData('/afs/cern.ch/user/m/masmith/private/year-4/VELO/2010/collision10.py', j.application)
INFO     Started parsing input Data file
ERROR    PythonOptsCmakeParserError:
[Errno 2] No such file or directory: ''
ERROR    Error: ApplicationConfigurationError: Unable to parse the job options. Please check options files and extraopts.
```

**Comment by rob-c** [comment]
@mesmith75 Is there a quick example file I can use to try and debug this?

**Comment by mesmith75** [comment]
@rob-c Sure I have put the collision10.py into /afs/cern.ch/user/m/masmith/public/forRob/

**Comment by rob-c** [comment]
@mesmith75 This PR should now fix your problems.
I'm testing this with the following:
```
j=Job(application=prepare_cmake_app('DaVinci','v41r3'));j.application.readInputData('collision10.py')
from Ganga.GPIDev.Lib.File.FileBuffer import FileBuffer
j=Job(application=prepareGaudiExec('DaVinci','v41r3'));j.application.options=[LocalFile(FileBuffer('hello.py','print("hello")'))];j.submit()
```

I've also added a new external test for the `GaudiExec` which test the `readInputData` as well as the ability to prepare and submit a local Job.
I'll look into improving the nightlies today/tomorrow so that any breaks in this show up clearer in future.

I was hoping to have a mocked test for the `GaudiExec` app ready sooner but this app does a lot of I/O and other things so mocking away all of the function calls for higher level functions is slightly time consuming to get right.

**Comment by mesmith75** [comment]
@rob-c Thanks, that works for me.

**Comment by rob-c** [comment]
Any objections to merging?

**Comment by mesmith75** [comment]
Not from me.

**Pull request merged**
