### PR TITLE
Tasks fixes for other plugins

### LINKED ISSUE #366: LHCb tasks bug
I'm seeing the following on startup:

```
2016-04-08 17:01:20,890 MainThread Ganga.Utility                      :264 ERROR   : problems with loading Named Templates for GangaLHCb
2016-04-08 17:01:20,891 MainThread Ganga.Utility                      :265 ERROR   : Reason: name 'taskify' is not defined
```

Does anyone else know if this is serious or not?

Thanks,

Rob

### PR DESCRIPTION
**Pull request by drmarkwslater**
Removes redundant code associated with old Tasks code. Fixes #366.

### CODE REVIEW

**Comment by milliams** [comment]
Wow, great job. I think this is a record for most lines of code removed in a PR so far.

:+1:

**Comment by rob-c** [comment]
Can we get a simple example of each even if it can't yet be part of the integration tests

**Comment by drmarkwslater** [comment]
Do you mean as testing code or just showing as an example? If it's the latter, could you create an issue and I'll add it to the docs.

**Comment by rob-c** [comment]
@drmarkwslater Just an example script which constructs a task and performs some common things with it.
If possible it would be nice to have a test for LHCb/Atlas which can be run by hand in an LHCb/Atlas environment as I think this isn't supported on Jenkins yet.

**Comment by rob-c** [comment]
If this can execute tasktest.zip from #173 I'm happy to close #173 and #179 with this After looking through #179 aside from post-processor stuff which is on the table to be fixed properly elsewhere there are no changes I'm wanting to fight for inclusion for.

**Comment by drmarkwslater** [comment]
Any objections to merging this?

**Comment by milliams** [comment]
:+1:

**Pull request merged**
