### PR TITLE
Remove deprecation warning

### PR DESCRIPTION
**Pull request by mesmith75**
So we don't forget.

### CODE REVIEW

**Review by egede — COMMENTED** [review]
I think we should change this to Python version 3.6 or higher. We have never tested it on anything below and there are still a few python 3.5 versions hanging around in distributions.

**Comment by alexanderrichards** [comment]
@mesmith75 should this PR not be targeting the python3 branch?

**Comment by mesmith75** [comment]
@alexanderrichards Ah yes - when I made the PR the deprecation warning was not in that branch yet. I'll rebase.

**Comment by mesmith75** [comment]
I guess we can merge this now?

**Review by egede — APPROVED** [review]

**Comment by egede** [comment]
Yes, this can be merged.

**Pull request merged**
