### PR TITLE
noop

### PR DESCRIPTION
**Pull request by mesmith75**
noop

### CODE REVIEW

**Review by alexanderrichards — APPROVED** [review]
What's this for?

**Comment by mesmith75** [comment]
Trying to figure out what's gone wrong with the testing

**Comment by alexanderrichards** [comment]
when I click the link to the tests for this PR it says they passed but it'e reporting failed to build to github. Is that the problem your seeing or are the Dirac tests still hanging?

**Comment by mesmith75** [comment]
```
Error when executing always post condition:
java.lang.NoSuchMethodError: No such DSL method 'cobertura' found among steps 
```

**Pull request closed without merging**
