### PR TITLE
Bugfix/lh cb splitting improvements

### PR DESCRIPTION
**Pull request by rob-c**
This relies on #117 so I'm not going to detail the changes which are in there which are in here.

The changes specific to this branch are minor and effect splitting LHCb jobs as it's some minor optimisations which effect this.

### CODE REVIEW

**Comment by milliams** [comment]
This PR repeats a lot of the changes from #117 and I'm not going to review the same changes twice while trying to work out which changes are different. Rebase this branch on develop once #117 is merged and then repoen this PR

**Comment by rob-c** [comment]
github automatically does that

**Comment by milliams** [comment]
Ok, then I will come back to this one once #117 is in.

**Comment by milliams** [comment]
:+1:

Now that this has had the changes from #117 merged in it looks good to me. Go ahead and merge whenever you are ready.

**Pull request merged**
