### PR TITLE
Change the input file used depending on the input type

### PR DESCRIPTION
**Pull request by drmarkwslater**
Hammercloud need to have the input file specified in a different way if they are checking directIO. This does that.

### CODE REVIEW

**Comment by mesmith75** [comment]
Is this ready to be merged for the release?

**Comment by drmarkwslater** [comment]
I'm still waiting on the HC team OK'ing this change so postpone for the moment.

**Comment by mesmith75** [comment]
Is this still for 6.2.1?

**Comment by mesmith75** [comment]
Can I merge this?

**Comment by mesmith75** [comment]
I'll bump to 6.2.2 for now.

**Comment by mesmith75** [comment]
Is this going in at some point?

**Pull request merged**
