### PR TITLE
Changed little ganga to use getProxyClass(cls) to avoid error

### PR DESCRIPTION
**Pull request by drmarkwslater**
Very minor change to avoid errors to do with objects not having the '_proxyClass' member.

### CODE REVIEW

**Comment by milliams** [comment]
:+1:

**Comment by rob-c** [comment]
Can we drop this to 6.1.18 if we're not advertising little ganga use yet?

**Comment by drmarkwslater** [comment]
We can I suppose but it doesn't touch any of the main code base and would make my life easier with creating the tutorial tests.

**Comment by milliams** [comment]
I think we should go ahead and merge this. It won't affect anything negatively but will at least allow `import ganga` to succeed.

**Comment by rob-c** [comment]
In this I say go for merge so we can get 6.1.17 out

**Pull request merged**
