### PR TITLE
Remove a whole load of refs to tagdataset

### PR DESCRIPTION
**Pull request by drmarkwslater**
It's not all of the TAG stuff gone but we're getting there.

### CODE REVIEW

**Comment by drmarkwslater** [comment]
Any chance this could be approved please?

**Comment by alexanderrichards** [comment]
Can one of the admins verify this patch?

**Comment by alexanderrichards** [comment]
Can one of the admins verify this patch?

**Comment by mesmith75** [comment]
Can we merge this?

**Comment by mesmith75** [comment]
Can we merge this?

**Pull request merged**
