### PR TITLE
Search registry by identity in find()

### LINKED ISSUE #426: Why is Registry find again comparing large Ganga objects behind the scenes?
https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/Core/GangaRepository/Registry.py#L489

I'm slightly concerned that I'm seeing this line in testing. There have been bugs in the ```__eq__``` methods in the past and this is extremely expensive which is why the find operation was at some point rewritten to just compare objects based upon ```_registry_id``` which is assigned at runtime.

This is partly to blame for: http://ganga.web.cern.ch/ganga/release/6.1.19-pre/reports/latest/html/summary_Ganga.old_test.Schema.html

Can we remove this assert as I'm not expecting it to be here?

### PR DESCRIPTION
**Pull request by milliams**
Fixes #426

### CODE REVIEW

**Comment by milliams** [comment]
Any problems with merging this?

**Comment by rob-c** [comment]
go from me, I'm wondering if this was a source of a performance improvement or whether the drop to 15min for the tests was conincidence

**Comment by milliams** [comment]
I would not be surprised if this allowed a slight performance improvement but I'd be surprised if all of the 19→15 minutes changes was due to this.

**Comment by rob-c** [comment]
It is called whenever there is a ```getNodeIndexCache``` which is called more than we'd like to admit so it may, but lets wait and see.

**Comment by milliams** [comment]
Looking at the [test time trend](https://ganga-ci.cern.ch/jenkins/job/PR%20builder/buildTimeTrend), it looks like the 19→15 minute time is holding well. I guess it was this PR that was responsible for the 25% speed improvement.

**Comment by rob-c** [comment]
Could this just be 25% of the tests weren't migrated, I've not checked the history.

**Comment by milliams** [comment]
Ah, that could indeed be related. It happened at a similar time.

**Pull request merged**
