### PR TITLE
Allow assignment of lists to PostProcessors

### LINKED ISSUE #385: GangaList has no attribute "execute"
To work-around GangaList not having the attribute "append" ([GANGA-270](https://github.com/ganga-devs/ganga/issues/270), supposed to be fixed by [GANGA-179](https://github.com/ganga-devs/ganga/pull/179)), I prepared the list of postprocessors in a normal python list and added all of them in one go:
```
j = Job(name='something')
...
postprocessors = [ FileChecker(files=['stdout'], searchStrings=['INFO Application Manager Terminated successfully'], failIfFound=False, checkMaster=False) ]
if args.evtmax < 0:
  postprocessors.append(LHCbCompleteChecker())
  if all(isinstance(f, LogicalFile) for f in j.inputdata):
    postprocessors.append(LHCbBookkeepingChecker())
j.postprocessors = postprocessors[:]
```
These jobs submit and seem to run normally, but fail when trying to run the postprocessor:
```
Ganga.Core.GangaThread.WorkerThreads: ERROR Exception raised executing 'job_finalisation' in Thread 'Job 207.5 Finalizing':
Traceback (most recent call last):
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 114, in __worker_thread
    result = item.command_input.function(*these_args, **item.command_input.kwargs)
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/GangaDirac/Lib/Backends/DiracBase.py", line 666, in job_finalisation
    job.force_status('failed')
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 1919, in force_status
    raise x
JobStatusError: JobStatusError: (AttributeError("'GangaList' object has no attribute 'execute'",),) 
```
Before the error, Ganga tries 5 times to get around this, with the following, slightly more verbose, warning:
```
Ganga.Utility.logging : WARNING ---------- error in user/extension code ----------
Ganga.Utility.logging : WARNING Traceback (most recent call last):
Ganga.Utility.logging : WARNING File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 609, in updateStatus
Ganga.Utility.logging : WARNING newstatus = self.transition_update(newstatus)
Ganga.Utility.logging : WARNING File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 648, in transition_update
Ganga.Utility.logging : WARNING passed = self.postprocessors.execute(self, new_status)
Ganga.Utility.logging : WARNING File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Adapters/IPostProcessor.py", line 111, in execute
Ganga.Utility.logging : WARNING process_result = p.execute(job, newstatus, **options)
Ganga.Utility.logging : WARNING AttributeError: 'GangaList' object has no attribute 'execute'
Ganga.Utility.logging : WARNING --------------------------------------------------
Ganga.GangaDirac.Lib.Backends : WARNING An error occured finalising job: 207.5
Ganga.GangaDirac.Lib.Backends : WARNING Attemting again (2 of 5) after 2.5-sec delay
```

### PR DESCRIPTION
**Pull request by drmarkwslater**
This allows the following to work:

```
        tm = TextMerger(files=['stdout'],compress = True)
        rm = RootMerger(files=['thesis_data.root'],args = '-f6')
        fc = FileChecker(files = ['stdout'],searchString = ['Segmentation'])
        cc = CustomChecker(module = '~/mychecker.py')
        n = Notifier(address = 'myadress.cern.ch')

        j.postprocessors = [tm,rm,fc,cc,n]
```

Fixes #385

### CODE REVIEW

**Comment by rob-c** [comment]
Just nit-picking here, is it possible to not use the ```__construct__``` method here?
I only ask as I'd really like to see this method go away in the near future as it makes it confusing where things are actually initialized.

If it's not possible to avoid it and it means re-writing another class I say leave it for another PR to make things clearer.

Other than this, it looks good to merge from me :+1:

**Comment by drmarkwslater** [comment]
It's possible but it makes things rather ugly as you have to check for lists of lists (of lists of lists...). Some proper recursion would really be needed so I thought I'd leave it here for now. Plus, I realise that all of this stuff is changing soon anyway so wasn't too worried :smile:

Anyway, I'd have a mild preference for keeping it where it is for neatness reasons but can shift it if people want.

**Comment by rob-c** [comment]
Nope, I'm perfectly happy with this being where it is, I was simply wondering if the functionality was available without calling ```__construct__``` if this is the best solution keep this as it is for now and I think we can change this in a future PR if needed :)

**Comment by drmarkwslater** [comment]
Sorry - completely misunderstood what you were saying as I thought you meant to shift this check into the `__construct__` function. So actually, at present I don't think there's a way to do it without `__construct__` but then saying that, I don't see why in general, code in `__construct__` isn't just in `__init__`. As you say, probably better addressed in another PR 😄

**Comment by drmarkwslater** [comment]
Sorry - completely misunderstood what you were saying as I thought you meant to shift this check into the `__construct__` function. So actually, at present I don't think there's a way to do it without `__construct__` but then saying that, I don't see why in general, code in `__construct__` isn't just in `__init__`. As you say, probably better addressed in another PR 😄

**Pull request merged**
