### PR TITLE
Update gangarc on minor version change

### LINKED ISSUE #1045: Change gangarc questions to minor version
Reminder to change the `.gangarc` questioning to when the minor version is updated.

### PR DESCRIPTION
**Pull request by mesmith75**
Fixes #1045 . 

As an aside would it be better to put the .used_versions file into the home directory? It is kind of annoying to have the gangarc updating when using different gangadirs .

### CODE REVIEW

**Comment by egede** [comment]
Moving the file out of the `gangadir` is a good idea. Now should it go straight in the home directory or should it go into `.cache/Ganga` ?

**Comment by mesmith75** [comment]
As the filename is not obviously ganga related I think the .cache/Ganga is best if its existence is verified earlier in the startup.

**Comment by mesmith75** [comment]
restest this please

**Comment by mesmith75** [comment]
Ok, so the `.used_versions` has been moved to `~/.cache/Ganga/`. If there are no objections I'll merge this for 6.6.2

**Pull request merged**
