### PR TITLE
Python3

### LINKED ISSUE #1485: Migrate Ganga to python3
We have decided to migrate Ganga to python3. @alexanderrichards has already made very good progress on the Core, Dirac and LHCb packages. The idea is that when these packages are done (which reflect the absolute majority of the use), the shift will be made. There will be no attempt to keep python2 compatibility. The the Ganga 7 series will be terminated as the last one to have python2 compatibility and the Ganga 8 series will only have python3 compatibility.

@JacekHoleczek Any effort available to update the T2K package over the next few weeks? Otherwise it will most likely sit in the code tree of Ganga 8 but fail to load until updated.

### PR DESCRIPTION
**Pull request by alexanderrichards**
Ok I think that we are basically ready to go on this. As we discussed we will hold off doing the actual release until Friday

Before Merging, check the following:
- [x]  Merge #1499 into devel
- [x]  Release 7.1.15 from develop and merge #1507 into develop afterwards.
- [x]  Merge develop back into python3
- [x]  Merge #1511 & #1509 into python3

---
This PR closes https://github.com/ganga-devs/ganga/issues/1485

### CODE REVIEW

**Comment by alexanderrichards** [comment]
Ok so unless anyone has any last minute objections I'll go ahead and do this merge.

**Comment by alexanderrichards** [comment]
looks like we need #1511 merged in here first

**Comment by mesmith75** [comment]
Please don't merge - we need to do the 7.1.15 release from develop first

**Comment by alexanderrichards** [comment]
> Please don't merge - we need to do the 7.1.15 release from develop first

Ah my bad, I though I saw the email saying you had done it already. As I mentioned we need to wait for 1511 anyway

**Comment by mesmith75** [comment]
I think we need to go in steps:

1. Release 7.1.15 from develop and merge #1507 into develop afterwards.
2. Merge python3 into develop along with #1509 and #1511 plus probably #1499.
3. Update the 8.0.0 release branch and then release.

Due to the deprecation warning in 7.1.15 I think we want to minimise time between releases.

**Comment by alexanderrichards** [comment]
Agreed although I would make step 2 more explicit:

1. Merge #1499 into devel
2. Release 7.1.15 from develop and merge #1507   into develop afterwards.
3. Merge develop back into python3
4. Merge #1511 & #1509 into python3
5. Merge python3 into devel
6. Update the 8.0.0 release branch and then release.

**Comment by alexanderrichards** [comment]
I think we probably want #1499 in the last python2 release right so we should merge first?

**Comment by mesmith75** [comment]
Yes I think that might be best.
#1509 is for the python 3 release, so I think it needs to go into step 4.

**Comment by alexanderrichards** [comment]
thanks, I'll update and put them as criteria in the head of this PR

**Comment by alexanderrichards** [comment]
@mesmith75 can we merge #1507 into develop now? Then we will need to merge develop back in here one last time.

**Comment by mesmith75** [comment]
No. The release is done from that branch. The release process sorts the notes and version numbers etc and will push back to the branch. Then we merge it into develop.

**Comment by alexanderrichards** [comment]
ok so looks like we are nearly there. Just got to release 7.1.15 and merge #1507 right?

**Comment by mesmith75** [comment]
I think we can merge this once the tests complete.

**Review by mesmith75 — APPROVED** [review]

**Pull request merged**
