### PR TITLE
Branch for release 7.0.0

### PR DESCRIPTION
**Pull request by mesmith75**
Release notes.

### CODE REVIEW

**Review by egede — APPROVED** [review]

**Comment by mesmith75** [comment]
test this please

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
If there are no objections I will release this...

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
test this please

**Comment by mesmith75** [comment]
@egede @alexanderrichards This has been released to pip and AFS but not to CVMFS. There are some corrections here for the release and one irritating bugfix in the boostrap.

It turns out the bootstrap checks the major version number so currently it complains that the gangarc was created by a development version as the major number is not 6.
```python
ERROR    file /home/mark/.gangarc was created by a development release (Ganga-7-0-0)
ERROR    try -g option to create valid ~/.gangarc
```

I propose therefore we merge this and send out 7.0.1 straight away with that fix in before release that to CVMFS. Any objections.

**Comment by egede** [comment]
Go for it.

**Pull request merged**
