### PR TITLE
Removed delay_lock_mod function which hung on no filelock FS

### LINKED ISSUE #465: Ganga should fail gracefully on an FS without File Locks
At present, if you try to start Ganga on a file system without file locks, it hangs in the Session lock. See #463. This seems like something we should allow to work.

### PR DESCRIPTION
**Pull request by drmarkwslater**
It was found in #463 that if you run Ganga on an FS without file locks, it hangs. I'm not sure of the exact reason for this but I'm assuming it's to do with the `delay_lock_mod` function which attempts to lock a file many times. In theory, this should fail eventually but that doesn't seem to be what's happening. Looking at the `fcntl` docs and what happened when running the `fcntl.lockf` function in plain python, if it can't acquire a lock straight away then it doesn't seem necessary to keep trying as it probably will never acquire a lock. 

The testing works on my machine and so I believe this to be safe. Let me know if not!

Fixes #465

### CODE REVIEW

**Comment by milliams** [comment]
I'm going to guess that AFS silliness was the cause for the attempt at delayed locking.

**Comment by drmarkwslater** [comment]
Possibly - but this code was specifically called when NOT on AFS 😄

**Comment by drmarkwslater** [comment]
Any issues with merging?

**Comment by milliams** [comment]
Go for it.

**Pull request merged**
