### PR TITLE
Change splitter for subjobs

### LINKED ISSUE #1669: Enable resubmission of subjobs with a new splitter
If a job is created with a splitter, it will create multiple subjobs. If some of the subjobs fail, it is possible to resubmit them, but not with a modification of the splitter. It can be very inefficient to resubmit the entire job with a new splitter. It should be possible to take a number of subjob and essentially run a new splitter on it. This might then create a number of subjobs that replace the existing one.

Imagine that we have a job where it carries out some calculation for a given integer parameter. We make a splitter that parts them such that each subjob does three calculations.

```
j = Job(splitter=ArgSplitter([[1,2,3],[4,5,6],[7,8,9]])
j.submit()
```
Now it turns out that the subjob wirh `[7,8,9]` failed because it ran out of some resource (memory, CPU time, ...) but it can be fixed by splitting it up into three separate pieces. At the moment I can only do that by creating a copy of the subjob and re-split.

```
j2 = j.subjobs[2].copy()
j2.splitter = ArgSplitter([[7],[8],[9]])
j2.submit()
```
While this works, it is unfortunate as it destroys the bookkeeping part (I now have to remember that my calculation is in both `j` and `j2`. If instead I could do

```
j.subjobs[2].splitter = ArgSplitter([[7],[8],[9]])
j.subjobs[2].submit()
```
I would end up with a single jobs object `j`, that now has 5 subjobs (I removed one by resplitting and created 3 new ones). Bookkeepoing would be much better as a result.

### PR DESCRIPTION
**Pull request by acampove**
Hi,

**Problem:** Given a job that has e.g. 100 subjobs each subjob might process 20 files. If one file is broken or unavailable in a specific site the whole 20 files won't be processed.

**Solution:** Allow for subjobs to be _resplit_ in such a way that the subjob will create 20 sub-subjobs, each processing one file. This should allow for the backend of the subjobs to be changed and therefore a different site to be used.

**Code:**

This fork allows to do:

```python
#It should work for any splitter
spl=ArgSplitter()
spl.args=[[1],[2],[3]]

#Pick up some job and subjob.
j=jobs(123)
sj=j.subjob[2]
sj.resubmit(splitter=spl)
```

The last line should allow the master job to create extra subjobs according to the `spl` splitter and submit them. The naming of the new subjobs should be as 

`123.2.0`
`123.2.1`
`123.2.2`

etc.

**Potential problem:** Although the jobs do run and finish, I do not seem to be able to run the monitoring on them by doing:

```python
j.jobs(997)
sj=j.subjobs[1]
slc=sj.subjobs
runMonitoring(slc)
```

image

Am I doing anything incorrectly or is this a problem in the code that needs to be fixed?

Cheers.

### CODE REVIEW

**Comment by alexanderrichards** [comment]
linking this to the relevant issue https://github.com/ganga-devs/ganga/issues/1669

**Comment by alexanderrichards** [comment]
Thanks for working on this @acampove.

@egede @mesmith75 My concern here is if we are allowing sub-subjobs and the fqid now has an additional dot in it, will this cause issues if we are splitting on this dot anywhere? We should be careful going forward to be aware of this

**Comment by mesmith75** [comment]
I am not sure this is what we had in mind.

Really we want to create new subjobs from the split and delete the original subjob. The monitoring won't work because it only looks at jobs and subjobs. I can imagine that adding an extra sub-subjob layer will require altering vast amounts of the code to work properly.

**Comment by alexanderrichards** [comment]
> I am not sure this is what we had in mind.
> 
> Really we want to create new subjobs from the split and delete the original subjob. The monitoring won't work because it only looks at jobs and subjobs. I can imagine that adding an extra sub-subjob layer will require altering vast amounts of the code to work properly.

This was my concern. I think creating replacement subjobs is a better idea

**Comment by acampove** [comment]
We can create subjobs from the master job. If you look at the older commit from my branch, you can see that it was implemented that way. However calling `_doSplit` (or something like that) from the master will make the splitter take the dataset from the master job when using `SplitByFile`. Writting the code to change that seemed harder than creating sub-sub jobs. Also keeping the new jobs as subjobs of the jobs that failed seems to make sense, it keeps the relationship between failed job-> replacement job. In any case, I will think of this.

**Comment by egede** [comment]
Great to see this work. A few specific comments below

- As already mentioned by @alexanderrichards and @mesmith75, the sub-subjobs structure is no good. While it might be an easier change locally in the `Job.py` file, it has far reaching consequences elsewhere.
- The subjobs that are being replaced should go into the `frozen_failed` state. 
- Calling `j.resubmit(splitter=spl)` more than once results in an error. See output below.

```python
[15:02:05]
Ganga In [46]: j = Job()
[15:02:08]
Ganga In [47]: j.submit()
INFO     submitting job 3
INFO     job 3 status changed to "submitting"
INFO     Job 3's application has already been prepared.
INFO     Preparing subjobs
INFO     submitting job 3 to Local backend
INFO     job 3 status changed to "submitted"
Ganga Out [47]: 1

[15:02:12]
Ganga In [48]: 

[15:02:13]
Ganga In [48]: j.subjobs
Ganga Out [48]: 
Registry Slice: jobs(3).subjobs (0 objects)


[15:02:17]
Ganga In [49]: j.resubmit(splitter=spl)
INFO     job 3 status changed to "running"
INFO     Job 3 Running PostProcessor hook
INFO     job 3 status changed to "completed"
INFO     removing: /tmp/tmpn5a_jznj
INFO     resubmitting job 3
INFO     Splitting Job: 3
INFO     submitting 3 subjobs
INFO     submitting job 3.0
INFO     job 3 status changed to "submitting"
INFO     Job 3.0's application has already been prepared.
INFO     submitting job 3.0 to Local backend
INFO     job 3 status changed to "submitted"
INFO     submitting job 3.1
INFO     job 3 status changed to "submitting"
INFO     Job 3.1's application has already been prepared.
INFO     submitting job 3.1 to Local backend
INFO     job 3 status changed to "submitted"
INFO     submitting job 3.2
INFO     job 3 status changed to "submitting"
INFO     Job 3.2's application has already been prepared.
INFO     submitting job 3.2 to Local backend
INFO     job 3 status changed to "submitted"

[15:02:23]
Ganga In [50]: j.subjobs
Ganga Out [50]: 
Registry Slice: jobs(3).subjobs (3 objects)
--------------
    fqid |    status |      name | subjobs |    application |        backend |                             backend.actualCE |                       comment |  subjob status 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     3.0 | completed |           |         |     Executable |      Localhost |                                       laptop |                               |            --- 
     3.1 | completed |           |         |     Executable |      Localhost |                                       laptop |                               |            --- 
     3.2 | completed |           |         |     Executable |      Localhost |                                       laptop |                               |            --- 


[15:02:27]
Ganga In [51]: 

[15:03:29]
Ganga In [51]: j.resubmit(splitter=spl)
INFO     removing: /tmp/tmpmgmhs5n1
INFO     removing: /tmp/tmp08gcg_pc
INFO     job 3 status changed to "running"
INFO     Job 3 Running PostProcessor hook
INFO     job 3 status changed to "completed"
INFO     removing: /tmp/tmpcq1ezcfe
INFO     resubmitting job 3
INFO     Splitting Job: 3
INFO     submitting 6 subjobs
INFO     submitting job 3.3
INFO     job 3 status changed to "submitting"
INFO     Job 3.3's application has already been prepared.
INFO     submitting job 3.3 to Local backend
INFO     job 3 status changed to "submitted"
INFO     submitting job 3.4
INFO     job 3 status changed to "submitting"
INFO     Job 3.4's application has already been prepared.
INFO     submitting job 3.4 to Local backend
INFO     job 3 status changed to "submitted"
INFO     submitting job 3.5
INFO     job 3 status changed to "submitting"
INFO     Job 3.5's application has already been prepared.
INFO     submitting job 3.5 to Local backend
INFO     job 3 status changed to "submitted"

[15:03:31]
Ganga In [52]: j.subjobs
ERROR    !!Unknown/Unexpected ERROR!!
INFO     removing: /tmp/tmplhx687hz
INFO     removing: /tmp/tmpk_lw4m2j
INFO     job 3 status changed to "running"
INFO     Job 3 Running PostProcessor hook
INFO     job 3 status changed to "completed"
INFO     removing: /tmp/tmpat1f_zrq
ERROR    If you're able to reproduce this please report this to the Ganga developers!
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/tmp/ganga/ganga/ganga/GangaCore/GPI/__init__.py in <module>
----> 1 j.subjobs

~/tmp/ganga/ganga/ganga/GangaCore/GPIDev/Base/Proxy.py in _getattribute(self, name)
   1135                     implInstance._schema.hasItem(name) and \
   1136                     not implInstance._schema.getItem(name)['hidden']:
-> 1137                         returnable = addProxy(implInstance._attribute_filter__get__(name))
   1138             else:
   1139                 try:

~/tmp/ganga/ganga/ganga/GangaCore/GPIDev/Lib/Job/Job.py in _attribute_filter__get__(self, name)
    461 
    462         if name == 'subjobs':
--> 463             return self._subjobs_proxy()
    464 
    465         if name == "fqid":

~/tmp/ganga/ganga/ganga/GangaCore/GPIDev/Lib/Job/Job.py in _subjobs_proxy(self)
   2142                 #First clear the dictionary
   2143                 if subjob_slice.objects:
-> 2144                     del subjob_slice.objects[:]
   2145                 #Not put the objects back in
   2146                 for sj in self.subjobs:

~/tmp/ganga/ganga/ganga/GangaCore/Utility/external/OrderedDict.py in __delitem__(self, key, dict_delitem)
     70         # Deleting an existing item uses self.__map to find the link which is
     71         # then removed by updating the links in the predecessor and successor nodes.
---> 72         dict_delitem(self, key)
     73         link_prev, link_next, key = self.__map.pop(key)
     74         link_prev[1] = link_next

TypeError: unhashable type: 'slice'

[15:03:37]
Ganga In [53]: 

```

**Comment by egede** [comment]
Concept moved over to #1891 . Closed here with thanks for making it clear how easy this actually was to implement.

**Pull request closed without merging**
