### PR TITLE
report function: (deprecated function and error) fix

### LINKED ISSUE #1023: report function in API not working
The report function is giving an error:
```python
Ganga In [16]: report(jobs(1916))
ERROR    No module named config
INFO     job 1918 status changed to "running"
ERROR    !!Unknown/Unexpected ERROR!!
ERROR    If you're able to reproduce this please report this to the Ganga developers!
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/python/Ganga/GPI/__init__.pyc in <module>()
----> 1 report(jobs(1916))

/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/python/Ganga/Utility/feedback_report.pyc in report(job)
     37     import platform
     38 
---> 39     import Ganga.GPIDev.Lib.Config.config as config
     40     from Ganga.GPIDev.Base.VPrinter import full_print
     41 

ImportError: No module named config
```

### PR DESCRIPTION
**Pull request by RajatSingh95**
#1023 issue

### CODE REVIEW

**Comment by egede** [comment]
I marked this as "in progress". Please let us know when ready for review. Post a URL where an uploaded report can be viewed. We should also make sure to create a test case for the full report function in https://github.com/ganga-devs/ganga/tree/develop/ganga/GangaCore/test/GPI. Test of the individual parts should go into https://github.com/ganga-devs/ganga/tree/develop/ganga/GangaCore/test/Unit as unit tests.

**Comment by egede** [comment]
@RajatSingh95 Are you still working on this. If not, I will close the PR.

**Comment by RajatSingh95** [comment]
@egede  Yes I am still working.

**Comment by RajatSingh95** [comment]
@egede  I have created a public service for report function whose url is http://ec2-52-14-218-28.us-east-2.compute.amazonaws.com/server/
On calling report function, it returns a download url for the report which could be used by the developers. Report is saved in .tar.gz format.

Output:
```
INFO     Your error report was uploaded to ganga developers with the following URL. 
INFO     You may include this URL and the following summary information in your bug report or in the support email to the developers.
INFO     
INFO     ***http://ec2-52-14-218-28.us-east-2.compute.amazonaws.com/media/userreport2020-03-08-22:25:24.tar.gz***
INFO     
INFO     Ganga Version : 8.2.2
INFO     Python Version : 3.6.9
INFO     Operation System Version : Linux-5.3.0-40-generic-x86_64-with-Ubuntu-18.04-bionic
INFO     Application Name : Executable
INFO     Backend Name : Local
INFO     Python Path : /home/rajat/ganga/ganga:/home/external/google-api-python-client/1.1/noarch/python:/home/external/python-gflags/2.0/noarch/python:/home/external/httplib2/0.8/noarch/python:/home/external/ipython/1.2.1/noarch/lib/python
```

[http://ec2-52-14-218-28.us-east-2.compute.amazonaws.com/media/userreport2020-03-08-22:25:24.tar.gz](url)
This is an example of dowload url. I have added Test cases for report function and tested it.

Backend of this service have been kept in this repo: [https://github.com/RajatSingh95/report-server](url)

**Comment by egede** [comment]
There is an error in the testing. It might be that the test itself needs to be rewritten. 

```
=================================== FAILURES ===================================

____________________________ TestReport.testReport _____________________________


self = <GPI.TestReport.TestReport testMethod=testReport>


    def testReport(self):
        from GangaCore.GPI import Job
        from GangaTest.Framework.utils import sleep_until_completed, file_contains
        from GangaCore.Utility.feedback_report import report
        import os
        j = Job()
    
        self.assertTrue(not j.subjobs)
        self.assertEqual(len(j.subjobs), 0)
    
        j.submit()
    
        self.assertEqual(len(j.subjobs), 0)
    
        self.assertIn(j.status, ['submitted','running','completed'])
        self.assertTrue(sleep_until_completed(j, 60), 'Timeout on completing job')
>       response,file_path = report(j)

ganga/GangaCore/test/GPI/TestReport.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ganga/GangaCore/Utility/feedback_report.py:718: in report
    response = run_upload(server=uploadFileServer, path=resultArchive)
ganga/GangaCore/Utility/feedback_report.py:141: in run_upload
    return upload_file(path)
ganga/GangaCore/Utility/feedback_report.py:83: in upload_file
    return send_post(server, files)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

url = 'http://gangamon.cern.ch/django/errorreports'
files = {'file': '/tmp/tmpzzm237wj/reportsRepository/userreport2020-03-08-17:20:10.tar.gz'}

    def send_post(url, files):
        logger.debug("Sending Post to %s ,  containing %s" % (url, files))
    
        encoded_data = encode_multipart_formdata(files)
>       import requests
E       ModuleNotFoundError: No module named 'requests'

ganga/GangaCore/Utility/feedback_report.py:91: ModuleNotFoundError
----------------------------- Captured stdout call -----------------------------
```

**Comment by egede** [comment]
In the uploaded report I see the error 
```
[Errno 2] No such file or directory: '/home/rajat/.ipython-ganga/history'
```
This is caused by the `ipython` no longer stores the history in a plain text file. It would be good still to get the history of the lets say last 50 or 100 commands. There must be a way to obtain it from inside python instead of copying the file.

**Comment by egede** [comment]
My knowledge about EC2 is (embarrassingly) limited. I assume this server is just a temporary thing and not something that will stay there forever?

**Comment by RajatSingh95** [comment]
> There is an error in the testing. It might be that the test itself needs to be rewritten.
> 
> ```
> =================================== FAILURES ===================================
> 
> ____________________________ TestReport.testReport _____________________________
> 
> 
> self = <GPI.TestReport.TestReport testMethod=testReport>
> 
> 
>     def testReport(self):
>         from GangaCore.GPI import Job
>         from GangaTest.Framework.utils import sleep_until_completed, file_contains
>         from GangaCore.Utility.feedback_report import report
>         import os
>         j = Job()
>     
>         self.assertTrue(not j.subjobs)
>         self.assertEqual(len(j.subjobs), 0)
>     
>         j.submit()
>     
>         self.assertEqual(len(j.subjobs), 0)
>     
>         self.assertIn(j.status, ['submitted','running','completed'])
>         self.assertTrue(sleep_until_completed(j, 60), 'Timeout on completing job')
> >       response,file_path = report(j)
> 
> ganga/GangaCore/test/GPI/TestReport.py:21: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> ganga/GangaCore/Utility/feedback_report.py:718: in report
>     response = run_upload(server=uploadFileServer, path=resultArchive)
> ganga/GangaCore/Utility/feedback_report.py:141: in run_upload
>     return upload_file(path)
> ganga/GangaCore/Utility/feedback_report.py:83: in upload_file
>     return send_post(server, files)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> url = 'http://gangamon.cern.ch/django/errorreports'
> files = {'file': '/tmp/tmpzzm237wj/reportsRepository/userreport2020-03-08-17:20:10.tar.gz'}
> 
>     def send_post(url, files):
>         logger.debug("Sending Post to %s ,  containing %s" % (url, files))
>     
>         encoded_data = encode_multipart_formdata(files)
> >       import requests
> E       ModuleNotFoundError: No module named 'requests'
> 
> ganga/GangaCore/Utility/feedback_report.py:91: ModuleNotFoundError
> ----------------------------- Captured stdout call -----------------------------
> ```

I think this error is due to requests module not being added to setup requirements. In the testing error, I can still see the old url. I have commented down the new url in `GangaCore/__init__.py` . for the uploadServer variable.
Or else you can replace the uploadServer url with 
 http://ec2-52-14-218-28.us-east-2.compute.amazonaws.com/server/  and try it.

**Comment by egede** [comment]
> I think this error is due to requests module not being added to setup requirements. 

1. We need to discuss what kind of server to use for this at a developers meeting.
2. For the testing, it is actually best to have the tests such that they do not depend on external services at all. Can you use the `mock` module in python to test everything without that the external server is ever contacted?

**Comment by egede** [comment]
> Backend of this service have been kept in this repo: https://github.com/RajatSingh95/report-server

I get a 404 error on this page.

**Comment by RajatSingh95** [comment]
I just checked it.  https://github.com/RajatSingh95/report-server is accessible.

Regarding the test case, Is it okay to mock the full report function since the function depend on external services?

**Comment by egede** [comment]
> I just checked it. https://github.com/RajatSingh95/report-server is accessible.
OK, works now ...

**Comment by egede** [comment]
> Regarding the test case, Is it okay to mock the full report function since the function depend on external services?

No, not quite. What we would like to demonstrate is that it can collect all the required information and pack it up. So the ideal would be to just mock the calls to the server and the corresponding replies.

**Comment by RajatSingh95** [comment]
@egede From the points you suggested, I have mocked the calls to the server and the corresponding replies in Report test. And I have updated the block in report function to get last 20 commands from the code itself. I have added a requests module in the setup.py since I am using it in the report function.

**Review by egede — APPROVED** [review]
This looks great. There is now a need to create a permanent server. I will file a new request for that.

**Pull request merged**
