### PR TITLE
Fixing bug in old_tests

### PR DESCRIPTION
**Pull request by rob-c**
This bug was highlighted by looking through the old_tests that were run against 6.1.21.

At what point in the release process are these tests run? Was there an email saying where the test results are located? I think I may have missed that email as I can't find one in my inbox.

As it stands this looks like a bug against LHCb Tasks so I'll try and see if I can run some simple task examples for LHCb and if not I'll push out the release with a caveat for tasks users. (I'm hoping to avoid this)

### CODE REVIEW

**Comment by rob-c** [comment]
Are these tests supposed to be passing? Either way I imagine this particular bug to be an annoyance. I'm going to try and find an archived LHCbTask .py and try to run it as the tests are struggling.

**Comment by rob-c** [comment]
After some exploring this doesn't appear to be a 'major' bug but I'm not sure if the code in the Tasks example is representative of the way that some people will use the Tasks system.
I'll ask for the release 6.1.21 to LHCb later today and I think we should be ok with this issue in the release given the many other things it's addressing.

**Comment by rob-c** [comment]
Any objections to merging this and pushing for 6.1.22? @milliams Are you able to make the release?

**Comment by drmarkwslater** [comment]
@rob-c Matt is on holiday this week so won't be able to do the release until next week. Are you able to yourself?

**Comment by rob-c** [comment]
@drmarkwslater I've been looking into this, (emailed the dev list) This should be possible for me to do looking at things. I don't think I'll re-run the old tests as historically we haven't for bugfix style releases.

**Pull request merged**
