### PR TITLE
use asetup 'here' option in all releases

### PR DESCRIPTION
**Pull request by will-cern**
ok last attempt, then I am bored!

### CODE REVIEW

**Comment by egede** [comment]
From Will: To test:

```
asetup 20.20.8.8,here
cmt new_skeleton MyPackage
cmt find_packages
cmt compile
mkdir run; cd run
ganga athena --condor .... --extOutFile=PoolFileCatalog.xml MyPackage/MyPackageAlgJobOptions.py
```

**Comment by egede** [comment]
@drmarkwslater If we had a docker image with the ATLAS software (via cvmfs), it should be easy to build a test that always runs for things like this.

**Comment by egede** [comment]
@will-cern Thanks for the multiple iterations. The tests are indeed running correctly now.

**Comment by will-cern** [comment]
There is a docker image that contains cvmfs so that setupATLAS and then 'asetup' can be run inside it: https://hub.docker.com/r/atlas/atlas_external_cvmfs/

**Comment by mesmith75** [comment]
What is the status of this? Are we waiting for the ATLAS test to be set up?

**Comment by mesmith75** [comment]
test this please

**Review by mesmith75 — APPROVED** [review]

**Pull request merged**
