### PR TITLE
Update Atlas.ini

### LINKED ISSUE #1098: Simple lxbatch job fails with unknown module __future__
Hi,

Following instructions at: https://twiki.cern.ch/twiki/bin/viewauth/AtlasComputing/SoftwareTutorialxAODAnalysisInCMake

My simple job submits to lxbatch backend but fails with: 

```
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/afs/cern.ch/user/w/will/gangadir/workspace/will/LocalXML/0/0/input/./__jobscript__", line 2, in <module>
    from __future__ import print_function
ImportError: No module named __future__
```

(Also, the ganga monitoring does not seem to recognise that the job failed, it just leaves the state as 'submitted')

This issue is not encountered on a local institute machine when submitting to condor backend.

### PR DESCRIPTION
**Pull request by drmarkwslater**
Need to update the Atlas.ini reference to GLITE_SETUP to remove the hard-coded cvmfs reference and replace with an env variable that will always be around if they have setup the Atlas environement correctly.

Have also added a fix in LSF jobs not working with certain Athena releases. Fixes #1098

### CODE REVIEW

**Comment by mesmith75** [comment]
Can we merge this? I would like one more bugfix release this week before merging the optimise branch.

**Comment by alexanderrichards** [comment]
Can one of the admins verify this patch?

**Comment by alexanderrichards** [comment]
Can one of the admins verify this patch?

**Comment by drmarkwslater** [comment]
retest please

**Comment by drmarkwslater** [comment]
retest this please

**Comment by drmarkwslater** [comment]
retest this please

**Comment by drmarkwslater** [comment]
retest this please

**Comment by mesmith75** [comment]
I think we can ignore the GangaDirac-PR and GangaLHCb-PR - I believe they are testing the new system.

**Comment by alexanderrichards** [comment]
> I think we can ignore the GangaDirac-PR and GangaLHCb-PR - I believe they are testing the new system.

indeed sorry for the noise. Hoping the new system will be operational shortly. As they are not marked "required" you can safely ignore them.

**Comment by mesmith75** [comment]
Can we merge this?

**Comment by drmarkwslater** [comment]
Ah - OK. I've still got a possible addition to this given the thread at #1098. I'll let you know!

**Comment by mesmith75** [comment]
@drmarkwslater How is this looking?

**Pull request merged**
