### PR TITLE
doc changes

### PR DESCRIPTION
**Pull request by rob-c**
This is moving do changes out of a PR. The barrier to entry for editing these docs is still far too high imo. This takes time that's probably better spent populating a wiki out of other tasks.

I'm merging this once the tests pass.

### CODE REVIEW

**Comment by milliams** [comment]
Why isn't the information in the table put into the docstrings of `IGangaFile`? The information in the dev guide should be higher-level conceptual design documentation.

**Comment by rob-c** [comment]
This went in a while ago without comment. Where should this go I'm confused as there is little documentation on how to use the documentation which frankly just confuses me even more.

**Comment by rob-c** [comment]
I'm not going to document the IGangaFile interface until it's clear what belongs there. I'd rather have some place where we can edit/look/agree about what should or shouldn't be the standard and then make the changes else there would be a PR with lots of discussions about docs for the IGangaFile I fear.

**Comment by milliams** [comment]
If you just want a scratch space for discussion about interfaces then the wiki is the best place for it. The dev guide should be an authoritative source of design information.

**Comment by mesmith75** [comment]
Is this for the next release or shall we defer it?

**Pull request closed without merging**
