### PR TITLE
Pick latest DIRAC version for tests

### PR DESCRIPTION
**Pull request by mesmith75**

### CODE REVIEW

**Comment by mesmith75** [comment]
This queries the Dirac release notes on github for the latest version (ignoring pre-releases). That part seems to work but it fails elsewhere for what I assume is related to the latest Dirac release?

**Comment by egede** [comment]
@marianne013 Hi Daniela. For use from Ganga we try to set up the latest dirac_ui to be used against the DIRAC WMS at Imperial. We follow the instructions at https://www.gridpp.ac.uk/wiki/Quick_Guide_to_Dirac and install with `./dirac-install -r v7r1p2 -i 27 -g v14r11`. However, in the subsequent `dirac_configure` step, there is an error. Is this because the DIRAC WMS at Imperial can't work with this latest version of the `dirac_ui`?

```bash
[dirac] ~/tmp/dirac_ui-v7r1p2 % dirac-configure -F -S GridPP -C dips://dirac01.grid.hep.ph.ic.ac.uk:9135/Configuration/Server -I
Executing: /home/egede/tmp/dirac_ui-v7r1p2/DIRAC/Core/scripts/dirac-configure.py -F -S GridPP -C dips://dirac01.grid.hep.ph.ic.ac.uk:9135/Configuration/Server -I 
Checking DIRAC installation at "/home/egede/tmp/dirac_ui-v7r1p2"
Will update /home/egede/tmp/dirac_ui-v7r1p2/etc/dirac.cfg
Could not sync dir Cannot get URL for Framework/BundleDelivery in setup GridPP: RuntimeError('Option /DIRAC/Setups/GridPP/Framework is not defined',)

```

**Comment by marianne013** [comment]
A v7r1 UI does not work with the Imperial DIRAC server, this is one version to far. v7r0 might work (it definitely works for some things, but I never looked at it in ganga context.. We currently cannot upgrade to any v7 version as we rely on some features that do not work in v7 yet.

**Comment by egede** [comment]
OK, I have changed it such that we stick with version 6 for now.

**Review by egede — APPROVED** [review]

**Pull request merged**
