### PR TITLE
Set python version in ganga

### PR DESCRIPTION
**Pull request by mesmith75**
Helps if there are multiple available versions.

### CODE REVIEW

**Review by alexanderrichards — COMMENTED** [review]
we will have to change this for Python 3

**Comment by mesmith75** [comment]
Yes. It's just that on slc6 the first python in the PATH is 2.6.

**Comment by alexanderrichards** [comment]
> Yes. It's just that on slc6 the first python in the PATH is 2.6.

Fair enough. Although has this not caused issues before?

**Review by alexanderrichards — APPROVED** [review]

**Review by egede — APPROVED** [review]
Given the move to python3 very soon, I actually think it is a good idea to be explicit here.

**Pull request merged**
