### PR TITLE
update GangaND280 to nd280Ganga CMT as of 2016.06.06 10:21 UTC

### PR DESCRIPTION
**Pull request by JacekHoleczek**
Please commit asap.

### CODE REVIEW

**Comment by milliams** [comment]
@ganga-ci test this please

**Comment by drmarkwslater** [comment]
@JacekHoleczek It looks like I don't have rights to merge the latest updates from develop in - can you do that by just clicking 'update branch'? Then I'll merge the PR.

**Comment by JacekHoleczek** [comment]
So, I clicked the "Update branch" button ...

**Comment by drmarkwslater** [comment]
retest this please

**Comment by drmarkwslater** [comment]
Merged - thanks @JacekHoleczek

**Pull request merged**
