### PR TITLE
Migrate IGangaFile to Ganga.GPIDev.Adapters

### LINKED ISSUE #46: Move IGangaFile from Ganga/GPIDev/Lib/File/IGangaFile to Ganga/GPIDev/Adapters/IGangaFile
Hi all,

This is a minor task which has obvious repercussions of some imports needing fixing but is there any reason why the IGangaFile interface shouldn't be placed with other interfaces in Ganga.GPIDev.Adapters?

This is a relatively simple 'Friday afternoon' task to do one week so I don't think we should have it blocking 6.1.14 but it would be nice to change this imo,

Unless anyone has any good reasons not to fix this?

Thanks,

Rob

### PR DESCRIPTION
**Pull request by alexanderrichards**
This pull request closes #46 . As discussed we move the interface IGangaFile into the Adapters directory with all the others.

### CODE REVIEW

**Comment by alexanderrichards** [comment]
@ganga-devs/core I'll merge this when 6.1.14 is out and assuming everyone is happy with it

**Comment by milliams** [comment]
I'm happy as long as it works :+1:

**Comment by alexanderrichards** [comment]
Indeed :wink: I guess that was my round about way of asking someone who can run Atlas/LHCb plugings to also give it a quick test

**Comment by alexanderrichards** [comment]
I re-based this to incorporate changes that have been put into develop while waiting to merge. Original commit is available above, or here https://github.com/ganga-devs/ganga/commit/194638d3fa659503967339efaeb5531115ef4531

**Pull request merged**
