### PR TITLE
Fix old LHCb RT handlers to propagate parsed xml summary

### LINKED ISSUE #140: Metadata not populated for subjobs
I have a checker that fails with 6.1.14 because the metadata per job is missing. The strange thing is that the combined metadata for the master job is there. 
```
[09:33:40]
Ganga In [1]: j=jobs[-1]

[09:33:45]
Ganga In [2]: j.subjobs[0].metadata
Ganga Out [2]: <Ganga.GPIDev.Lib.Job.MetadataDict.MetadataDict at 0x7f19501e3b10>

[09:33:59]
Ganga In [3]: j.subjobs[0].metadata.data
Ganga Out [3]: {}

[09:34:07]
Ganga In [4]: j.metadata
Ganga Out [4]:
{
     xmldatafiles = {'full': set(['LFN:/lhcb/data/2015/RAW/LUMI/LHCb/LEAD15/169504/169504_0000000088.raw', ...,  'LFN:/lhcb/data/2015/RAW/LUMI/LHCb/LEAD15/169503/169503_0000000405.raw'])}
     xmldatanumbers = {'full': 49}
     lumi = Not Available.
     events = {'output': 0, 'input': 90383787L}
     xmlskippedfiles = set([])
    }
```
On a side note, subjobs are not returned as proxy objects, so it is annoying to work interactively with them.

### PR DESCRIPTION
**Pull request by rmatev**
This fixes #140 
If it can make it to 6.2.1 I would be very happy.

### CODE REVIEW

**Comment by milliams** [comment]
@ganag-ci test this please

**Comment by rob-c** [comment]
@rmatev Thanks for the contribution. I will make the comment here that we technically __no longer__ support the old application objects. That being said given this is a small fix I'm very happy to merge this into 6.2.1
@egede Do we want to stop accepting fixes for the old apps at some point?

**Comment by rmatev** [comment]
@rob-c I am aware since you mentioned this already, but I think `GaudiExec` is a bit shy in features to drop standard applications just yet.

PS I've started looking into implementing the summary.xml / metadata support in GaudiExec, but it is not exactly trivial due to (I think) a deeper issue with GaudiExec.

**Comment by rob-c** [comment]
@rmatev What are the features which `GaudiExec` requires in this case? I will try and find some time to get these implemented or templated for 6.3.0.

I see no deep issue with the `GaudiExec` class. If you're needing the XML summary to be parsed from the jobs I'm certain there is a solution for this that doesn't involve too much work. To what issue(s) are you referring?

**Comment by rmatev** [comment]
@rob-c, let's move the discussion to #764 if you don't mind

**Comment by rob-c** [comment]
@rmatev If you can update your branch to match ganga develop I'll merge this in for 6.2.1

**Comment by rmatev** [comment]
@rob-c thanks, it's done

**Comment by rob-c** [comment]
@ganag-ci test this please

**Comment by egede** [comment]
@rob-c Small user supplied bug fixes to the old application handlers will be accepted as long as they do not have side effects or will require significant developer time to implement.

**Pull request merged**
