### PR TITLE
Don't re-exec Ganga when running tests

### PR DESCRIPTION
**Pull request by milliams**
Re-execing is now not needed for most of Ganga and this was breaking the logging while running tests.

This change allows all logging messages to be correctly captured by the test framework.

@rob-c I believe this addresses the complaint you had last week about logging within tests.

### CODE REVIEW

**Comment by rob-c** [comment]
@milliams My complaint was that for failed tests the whole stdout/stderr isn't printed anywhere (or wasn't for some reason in some test I was looking at)

Either way, yes, keen to see this go, forgot this was enabled by default. Are we still looking to drop the re-exec code in the future?

**Comment by milliams** [comment]
For a failed test, the stdout is printed in a `-------- Captured stdout call -------` section by pytest. The problem was that all the logging messages emitted during the test were being filtered away and never directed to stdout.

I'm hoping to drop the re-exec as soon as possible. The thing stopping it happening already is that the ATLAS code relies on it for setting the PATH for running external commands. Of course technically this is fixable by passing an appropriate environment to `subprocess` but someone needs to do the actual work. See #52 for discussion on this.

**Comment by rob-c** [comment]
Can we look to disable this by default actually and change the Atlas config to still use it?

**Comment by milliams** [comment]
That's a good idea. I will take a look into this.

**Comment by rob-c** [comment]
For the time being I think we can safely merge this PR (It's only for the tests), disabling the re-exec by default sounds like another PR probably.

**Pull request merged**
