### PR TITLE
Fix for killing jobs and subjobs

### LINKED ISSUE #949: Killing a subjob updates the master status
Killing a single subjob updates the status of the master jobs and all the other subjobs to killed.

Only the statuses are updated - the other subjobs still run and complete.

### PR DESCRIPTION
**Pull request by mesmith75**
Fixes #949

### CODE REVIEW

**Comment by rob-c** [comment]
Would it be worth adding a quick test around this the code around the job state transitions is still a mystery to me.

**Comment by mesmith75** [comment]
yes, I'll add some in.

**Comment by mesmith75** [comment]
Something has gone very wrong with this. Killing the master job now fails with and error:
```python
Ganga In [3]: jobs(25).kill()
INFO     job 25 status changed to "running"
INFO     killing job 25
INFO     removing: /tmp/masmith/tmpO2z_RR
INFO     removing: /tmp/masmith/tmp4ZwtOW
INFO     removing: /tmp/masmith/tmpleuUBT
INFO     removing: /tmp/masmith/tmphZkNzT
INFO     removing: /tmp/masmith/tmpeyRj7k
INFO     job 25 status changed to "killed"
ERROR    failed to kill job 25: JobStatusError: forbidden status transition of job 25 from "killed" to "running"
ERROR    JobError: failed to kill job 25: JobStatusError: forbidden status transition of job 25 from "killed" to "running"
```

I assume it is the monitoring that is trying to return the job to running - do we need to put a lock around the killing?

**Comment by mesmith75** [comment]
Updating the master status after the subjob statuses fixes the issue,

**Comment by mesmith75** [comment]
I added a slight improvement to the test - just to make sure the job is running before killing it.

**Comment by mesmith75** [comment]
If this is still approved I'll merge it.

**Pull request merged**
