### PR TITLE
Release things

### PR DESCRIPTION
**Pull request by mesmith75**
testing the release

### CODE REVIEW

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
With the exception of the mailer I think this is working ok

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
test this please

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
do the release

**Comment by mesmith75** [comment]
test this please

**Comment by mesmith75** [comment]
Could someone please review this? We should probably get the next release out.

**Review by egede — APPROVED** [review]

**Pull request merged**
