### PR TITLE
Adding fix to enable splitting for files which don't appear to exist

### LINKED ISSUE #1223: Serious Bug in LHCb splitting
User reported problems with LHCb job splitting... interesting as I am convinced that this didn't happen outside of development when I wrote the splitter.

This means that the total number of files after the splitter has finished + the number of files which have been rejected due to not having valid replica != the number of files which the splitter was asked to split by.

I'm injecting some extra debug into the code to see if this suggests what has gone wrong but from intial inspection there is some problem in identifying the invalid lfns...

```
j=Job(inputdata=BKQuery('/LHCb/Collision11/Beam3500GeV-VeloClosed-MagDown/Real Data/Reco14/Stripping21r1/90000000/BHADRON.MDST').getDataset(),splitter=SplitByFiles(ignoremissing=True),backend=Dirac(blockSubmit=False))
j.submit()
```

Full log:
```
INFO     submitting job 157
INFO     job 157 status changed to "submitting"
INFO     Preparing Executable application.
INFO     Created shared directory: conf-473f4940-6765-4e6c-8708-0d3110b3b11b
INFO     Splitting Job: 157
INFO     Constructing subjobs
INFO     Requesting LFN replica info
INFO     Got Replica Info: [0:250] of 4549
INFO     Got Replica Info: [500:750] of 4549
INFO     Got Replica Info: [1000:1250] of 4549
INFO     Got Replica Info: [250:500] of 4549
INFO     Got Replica Info: [750:1000] of 4549
INFO     Got Replica Info: [2000:2250] of 4549
INFO     Got Replica Info: [1750:2000] of 4549
INFO     Got Replica Info: [1250:1500] of 4549
INFO     Got Replica Info: [1500:1750] of 4549
INFO     Got Replica Info: [2250:2500] of 4549
INFO     Got Replica Info: [2500:2750] of 4549
INFO     Got Replica Info: [3000:3250] of 4549
INFO     Got Replica Info: [2750:3000] of 4549
INFO     Got Replica Info: [3500:3750] of 4549
INFO     Got Replica Info: [3250:3500] of 4549
INFO     Got Replica Info: [3750:4000] of 4549
INFO     Got Replica Info: [4000:4250] of 4549
INFO     Got Replica Info: [4500:4549] of 4549
INFO     Got Replica Info: [4250:4500] of 4549
INFO     Got all good replicas
INFO     found all replicas
INFO     Calculating site<->SE Mapping
WARNING  LFN /lhcb/LHCb/Collision11/BHADRON.MDST/00041840/0000/00041840_00006963_1.bhadron.mdst has no site available and ignoremissing = true! Removing this LFN from the dataset!
WARNING  LFN /lhcb/LHCb/Collision11/BHADRON.MDST/00041840/0000/00041840_00007284_1.bhadron.mdst has no site available and ignoremissing = true! Removing this LFN from the dataset!
WARNING  LFN /lhcb/LHCb/Collision11/BHADRON.MDST/00041840/0000/00041840_00002130_1.bhadron.mdst has no site available and ignoremissing = true! Removing this LFN from the dataset!
WARNING  LFN /lhcb/LHCb/Collision11/BHADRON.MDST/00041840/0000/00041840_00002298_1.bhadron.mdst has no site available and ignoremissing = true! Removing this LFN from the dataset!
WARNING  LFN /lhcb/LHCb/Collision11/BHADRON.MDST/00041840/0001/00041840_00016560_1.bhadron.mdst has no site available and ignoremissing = true! Removing this LFN from the dataset!
INFO     Calculating best data subsets
INFO     Average Subset size is: 9.79310344828
ERROR    SERIOUS SPLITTING ERROR!!!!!
ERROR    SERIOUS SPLITTING ERROR!!!!!
ERROR    SERIOUS SPLITTING ERROR!!!!!
ERROR    SplitterError: Files Missing after Splitting!
ERROR    SplitterError: Files Missing after Splitting!
ERROR    SplitterError: Files Missing after Splitting! ... reverting job 157 to the new status
ERROR    SplitterError: Files Missing after Splitting! ... reverting job 157 to the new status
INFO     job 157 status changed to "new"
ERROR    JobError: Error: SplitterError: Files Missing after Splitting!
ERROR    JobError: Error: SplitterError: Files Missing after Splitting!
```

(Ignoring _for now_ that each error appears twice now from a clean lxplus login!)

### PR DESCRIPTION
**Pull request by rob-c**
Based on #1224  although can be re-based (but I'd like to push to merge this and a few outstanding smaller fixes).

This addresses splitting of jobs breaking with LFN with no valid replica as of #1203 .

Fixes #1223

### CODE REVIEW

**Comment by rob-c** [comment]
@mesmith75 I'm strongly leaning toward this being a ganga problem as the exception and the refusal to continue is thrown from within ganga with no bad information being returned by DIRAC.
The DIRAC devs asked if the API usage could be changed and there is different behaviour from the new `getReplicasForJobs` compared to the `getReplicas`. Ganga should take that into account if it's going to use the former method and should allow for jobs to be correctly split and submitted.

This problem can only occur if DIRAC is now reporting that these files have replicas but at no valid SE vs having no replicas when the SE is offline.
Combined with the statement of `Removing this LFN from the dataset!!` at https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaDirac/Lib/Splitters/OfflineGangaDiracSplitter.py#L223 this becomes more unexpected behaviour from the splitter in ganga and the fact that this can be fixed by users explicitly manually removing these files is proof of this.

Using the old API (Ganga 6.7.4) if DIRAC is reporting file replicas all of the time which are at invalid SE at the time of submission will lead to an increase in users seeing jobs stalling on the grid as their inputdata requirements cannot be met by the job matcher. This is potentially a change which comes from the running/version of DIRAC but either way my point that ganga isn't doing what it says correctly (it is removing the LFN from the dataset and then failing to report knowledge of this further into the splitting) holds, the test is correctly finding missing LFN lost in the splitting process and the exception thrown from ganga is highlighting this bug.

**Comment by mesmith75** [comment]
@rob-c Makes sense - I should have been more careful making that change I guess. Thanks for fixing it so quickly.

**Comment by rob-c** [comment]
I'll rebase on develop once #1194 has finished

**Comment by rob-c** [comment]
Tbh this is a change in undocumented _expected_ behaviour from the DIRAC API which can be annoying to whittle down. Only reason I think I know what's going on here is I wrote the splitter

**Comment by mesmith75** [comment]
@rob-c I think I understand what goes on but could you give a brief description of the logic here?

**Comment by rob-c** [comment]
@mesmith75 Added some docs to the file and added fixes from linting in vscode

**Comment by rob-c** [comment]
OK, I've just had a chat with Vladimir and I've been asked to make some minor tuning to the splitter to help improve the situation on the grid with regard to user jobs. I'll amend this PR accordingly.

**Comment by mesmith75** [comment]
@rob-c Great. What kind of timescale do you reckon - it would be nice to release this soon.

**Comment by rob-c** [comment]
OK, I've tuned this as much as it will allow.

Tbh given recent optimizations and the block submit code I suggest we seriously look at returning to the vanilla DIRAC splitter which although it used to make an excess of subjobs ganga is in a much better situation to cope with it now.

**Comment by mesmith75** [comment]
@rob-c Did you mean to close this?

**Comment by rob-c** [comment]
nope, I just got used to gitlabs buttons being the opposite way around I think, it's been a long day

**Comment by rob-c** [comment]
good to review whenever you get a chance
I ended up cleaning up the confusion around the duplicate exceptions here because trying to test this was annoyingly confusing with multiple exception types for the same reason

**Review by mesmith75 — APPROVED** [review]

**Comment by mesmith75** [comment]
Once you have merged this could you advertise it to distributed-analysis. The DEV version updates at midnight - it would be good to have some users testing it.

**Comment by rob-c** [comment]
@mesmith75 Can you please take a look at #1193 picking-up/fixing jobs in the submitting and completing state is still one of the main time consuming tasks when helping people with grid related problems.

**Comment by mesmith75** [comment]
@rob-c  can we merge this?

**Comment by rob-c** [comment]
Yeah, I'd be happy to merge this but the jenkins box isn't reporting statuses, I'd suggest checking a firewall over this but I'm happy to merge when it's fixed.

**Comment by mesmith75** [comment]
looks like it has crashed. @alexanderrichards how does one restart it?

**Pull request merged**
