### PR TITLE
Change default LHCbDirac version to v8r3p7

### PR DESCRIPTION
**Pull request by mesmith75**
Updating the LHCbDirac version

### CODE REVIEW

**Comment by rob-c** [comment]
Thanks, I'm updating the lhcb-prepare script once this goes in. We should be weary we still rely on SetupProject to deploy ganga to LHCb and this could blow up in our faces as LHCbDirac technically no longer supports SetupProject for the new cmake tools. Unfortunately I suspect we won't know the implication for this until we request the version be deployed for testing.

**Comment by mesmith75** [comment]
Good point - would it be best to go back to the last v8r2 release? If not then I'll merge this.

**Comment by rob-c** [comment]
@mesmith75 Imo we can't really dodge the bullet on it and we should look to move to LHCbDirac 8.3 sooner imo so if there are problems they're found sooner rather than later.
This only really effects LHCb and we can push out 6.2.2 if we reach a point that we discover that some serious work needs doing.

**Comment by mesmith75** [comment]
Ok, I'll merge this.

**Pull request merged**
