### PR TITLE
Never copy executable string

### PR DESCRIPTION
**Pull request by mesmith75**

### CODE REVIEW

**Comment by JacekHoleczek** [comment]
Please see: https://github.com/ganga-devs/ganga/issues/1401#issuecomment-455644446

**Comment by JacekHoleczek** [comment]
This looks almost great.
Just one note.
You write "If the string can be resolved to an existing file, ganga will copy the file to the sandbox to be shipped to the WN." but I think in case of a "string", it should never be copied to the sandbox, even if the file exists on the node where Ganga runs (in order to make sure that false "dummy" executables are not copied from the head node do WN). Only explicit "File('string')" should be copied.
That was actually the original idea, wasn't it: "When you want to execute a command on the worker node you should specify it as a string. Ganga will call the command with its full path on the worker node:"

Please again see (I added there another two cases when copying into sandbox needs to be prohibited): https://github.com/ganga-devs/ganga/issues/1401#issuecomment-455644446

**Comment by JacekHoleczek** [comment]
Could I have a question here, please.
In the [update docstring](https://github.com/ganga-devs/ganga/pull/1412/commits/1f2055ede427d1dfe1a51873280f56e859b50608) patch, I find: "In this case, a wrapper script which calls this same command is created and placed into the Shared Directory."
But I cannot locate the source code which does it in the other patch.
I just want to ask you the following ... when you create a wrapper script, please make sure that you use a ganga specific name for it ... like `'./_ganga_'+original_exe_name` (or `'./_sandbox_'+original_exe_name`).
I think we should not create a script with the same name as the original executable name ... just as a precaution for cases when the user prepends  the `os.environ["PATH"]` with "." in the "preexecute" string (and then somewhere in some script uses the `original_exe_name` without specifying the full path, for example, in order to "locate" its configuration files, data or modules).

**Comment by mesmith75** [comment]
test this please

**Comment by JacekHoleczek** [comment]
I'm afraid I would need some help ... how to get it into a new ganga distribution installed with "pip" (in a "virtualenv").

**Comment by JacekHoleczek** [comment]
I looked at the "changed file" ("Executable.py") and it seems to me that you need to "reverse" conditions in lines starting with 126 (well, "str" takes precedence and the "source" may not exist where the ganga executable runs):
```
            if isinstance(self.exe, str):
                logger.debug("exe is a string so no copying")
            elif not os.path.exists(source):
                logger.debug("Error copying exe: %s to input workspace" % str(source))
            else:
```

See: https://github.com/ganga-devs/ganga/pull/1421

**Review by egede — COMMENTED** [review]
Seems to have an overlap with #1421 . Maybe this PR can just be retired?

**Comment by JacekHoleczek** [comment]
Yes, I took this patch, tried it and found that I needed to patch yet another file in order to get it working (and a patch for both files is #1421  which got "mixed" yesterday with my new SLURM related patch).

There is one point which I did not cover. As written in one of my previous comments here.
I just want to ask you the following ... if you need to create a wrapper script, please make sure that you use a ganga specific name for it ... like `'./_ganga_'+original_exe_name` (or `'./_sandbox_'+original_exe_name`).

BTW. A corresponding patch for the old Ganga-6-0-4[432] is here: https://github.com/ganga-devs/ganga/issues/1401#issuecomment-462399166

**Pull request closed without merging**
