### PR TITLE
Fix files on the batch

### PR DESCRIPTION
**Pull request by mesmith75**
Prevents batch jobs trying to use ganga code when copying output

### CODE REVIEW

**Review by egede — CHANGES_REQUESTED** [review]
We have the capability to ship code along with the job and place it in a subdirectory. Would that be better here rahter than making the template longer.

**Comment by mesmith75** [comment]
So that is what we do currently. The problem is the code we ship is just a copy of https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/Utility/files.py so it fails when trying to import the ganga modules.
As we only use two functions I figured this would be the simplest solution

**Comment by egede** [comment]
It seems like the only import is the logger for a single debug statement. Can't we just delete that one? Anyway this is not a big deal either way. Your proposed solution is of course fine as well, but duplication of code should be avoided where possible.

**Review by egede — DISMISSED** [review]

**Comment by mesmith75** [comment]
Yes, that is better.

**Comment by mesmith75** [comment]
Could someone approve this please? It is messing up my analysis jobs at Imperial.

**Review by egede — APPROVED** [review]
Sorry, I forgot that I did not approve it first time round.

**Comment by mesmith75** [comment]
thanks!

**Pull request merged**
